# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ExportType(str, Enum):  # type: ignore[misc]
    """
    The types of Exporting capable of being delivered by the WebAPI. Similar but not identical to <seealso cref=\"T:Finbourne.Honeycomb.Api.Hosting.Exporting.OutputType\" />
    """

    """
    allowed enum values
    """
    CSV = 'csv'
    PIPE = 'pipe'
    EXCEL = 'excel'
    JSON = 'json'
    JSONPROPER = 'jsonProper'
    XML = 'xml'
    PARQUET = 'parquet'
    SQLITE = 'sqlite'
    TABLEINTERNAL = 'TableInternal'
    JSONPROPERWITHLINEAGE = 'jsonProperWithLineage'
    PDF = 'pdf'

    @classmethod
    def from_json(cls, json_str: str) -> ExportType:
        """Create an instance of ExportType from a JSON string"""
        return ExportType(json.loads(json_str))

