# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SqlExecutionFlags(str, Enum):  # type: ignore[misc]
    """
    SqlExecutionFlags
    """

    """
    allowed enum values
    """
    NONE = 'None'
    PROVIDELINEAGE = 'ProvideLineage'

    @classmethod
    def from_json(cls, json_str: str) -> SqlExecutionFlags:
        """Create an instance of SqlExecutionFlags from a JSON string"""
        return SqlExecutionFlags(json.loads(json_str))

