# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, TYPE_CHECKING
from datetime import datetime



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 


class AmazonSqsNotificationTypeResponse(BaseModel):
    """
    Holds readonly information about an AWS SQS notification  # noqa: E501
    """
    type:  Optional[StrictStr] = Field(default=None,alias="type", description="The type of delivery mechanism for this notification") 
    api_key_ref:  Optional[StrictStr] = Field(default=None,alias="apiKeyRef", description="Reference to API key from Configuration Store") 
    api_secret_ref:  Optional[StrictStr] = Field(default=None,alias="apiSecretRef", description="Reference to API secret from Configuration Store") 
    body:  Optional[StrictStr] = Field(default=None,alias="body", description="The body of the Amazon Queue Message") 
    queue_url_ref:  Optional[StrictStr] = Field(default=None,alias="queueUrlRef", description="Reference to queue url from Configuration Store") 
    __properties = ["type", "apiKeyRef", "apiSecretRef", "body", "queueUrlRef"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""

        # Finbourne have removed enum validation on all models, except for this use case:
        # Workflow and notification application SDK use the property name 'type' as the discriminator on a number of classes.
        # During instantiation, the value of 'type' is checked against the enum values, 
        

        # check it's a class that uses the 'type' property as a discriminator
        # list of classes can be found by searching for 'actual_instance: Union[' in the generated code
        if 'AmazonSqsNotificationTypeResponse' not in [ 
                                    # For notification application classes
                                    'AmazonSqsNotificationType',
                                    'AmazonSqsNotificationTypeResponse',
                                    'AmazonSqsPrincipalAuthNotificationType',
                                    'AmazonSqsPrincipalAuthNotificationTypeResponse',
                                    'AzureServiceBusTypeResponse',
                                    'AzureServiceBusNotificationType',
                                    'EmailNotificationType',
                                    'EmailNotificationTypeResponse',
                                    'SmsNotificationType',
                                    'SmsNotificationTypeResponse',
                                    'WebhookNotificationType',
                                    'WebhookNotificationTypeResponse',
                        
                                    # For workflow application classes
                                    'CreateChildTasksAction', 
                                    'RunWorkerAction', 
                                    'TriggerParentTaskAction',
                                    'CreateChildTasksActionResponse', 
                                    'RunWorkerActionResponse',
                                    'TriggerParentTaskActionResponse',
                                    'CreateNewTaskActivity',
                                    'UpdateMatchingTasksActivity',
                                    'CreateNewTaskActivityResponse', 
                                    'UpdateMatchingTasksActivityResponse',
                                    'Fail', 
                                    'GroupReconciliation', 
                                    'HealthCheck', 
                                    'LuminesceView', 
                                    'SchedulerJob', 
                                    'Sleep',
                                    'FailResponse', 
                                    'GroupReconciliationResponse', 
                                    'HealthCheckResponse', 
                                    'LuminesceViewResponse', 
                                    'SchedulerJobResponse', 
                                    'SleepResponse',
                                    'Library',
                                    'LibraryResponse',
                                    'DayRegularity',
                                    'RelativeMonthRegularity',
                                    'SpecificMonthRegularity',
                                    'WeekRegularity',
                                    'YearRegularity',
                                    'LusidEntityDataQualityCheck',
                                    'LusidEntityDataQualityCheckResponse',
                                    'TriggerChildTasksActionResponse']:
           return value
        
        # Only validate the 'type' property of the class
        if "type" != "type":
            return value

        if value is None:
            return value

        if value not in ['AmazonSqs']:
            raise ValueError("must be one of enum values ('AmazonSqs')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AmazonSqsNotificationTypeResponse:
        """Create an instance of AmazonSqsNotificationTypeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self. model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if type (nullable) is None
        # and model_fields_set contains the field
        if self.type is None and "type" in self.model_fields_set:
            _dict['type'] = None

        # set to None if api_key_ref (nullable) is None
        # and model_fields_set contains the field
        if self.api_key_ref is None and "api_key_ref" in self.model_fields_set:
            _dict['apiKeyRef'] = None

        # set to None if api_secret_ref (nullable) is None
        # and model_fields_set contains the field
        if self.api_secret_ref is None and "api_secret_ref" in self.model_fields_set:
            _dict['apiSecretRef'] = None

        # set to None if body (nullable) is None
        # and model_fields_set contains the field
        if self.body is None and "body" in self.model_fields_set:
            _dict['body'] = None

        # set to None if queue_url_ref (nullable) is None
        # and model_fields_set contains the field
        if self.queue_url_ref is None and "queue_url_ref" in self.model_fields_set:
            _dict['queueUrlRef'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AmazonSqsNotificationTypeResponse:
        """Create an instance of AmazonSqsNotificationTypeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AmazonSqsNotificationTypeResponse.model_validate(obj)

        _obj = AmazonSqsNotificationTypeResponse.model_validate({
            "type": obj.get("type"),
            "api_key_ref": obj.get("apiKeyRef"),
            "api_secret_ref": obj.get("apiSecretRef"),
            "body": obj.get("body"),
            "queue_url_ref": obj.get("queueUrlRef")
        })
        return _obj

AmazonSqsNotificationTypeResponse.model_rebuild()

