# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, TYPE_CHECKING
from datetime import datetime



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 
from finbourne.sdk.services.lusid.models.compliance_rule_result import ComplianceRuleResult
from finbourne.sdk.services.lusid.models.resource_id import ResourceId


class ComplianceBreachedOrderInfo(BaseModel):
    """
    ComplianceBreachedOrderInfo
    """
    order_id: ResourceId = Field(alias="orderId")
    list_rule_result: List[ComplianceRuleResult] = Field(description="The Rule Results for a particular compliance run", alias="listRuleResult")
    __properties = ["orderId", "listRuleResult"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ComplianceBreachedOrderInfo:
        """Create an instance of ComplianceBreachedOrderInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self. model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of order_id
        if self.order_id:
            _dict['orderId'] = self.order_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in list_rule_result (list)
        _items = []
        if self.list_rule_result:
            for _item in self.list_rule_result:
                if _item:
                    _items.append(_item.to_dict())
            _dict['listRuleResult'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ComplianceBreachedOrderInfo:
        """Create an instance of ComplianceBreachedOrderInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ComplianceBreachedOrderInfo.model_validate(obj)

        _obj = ComplianceBreachedOrderInfo.model_validate({
            "order_id": ResourceId.from_dict(obj.get("orderId")) if obj.get("orderId") is not None else None,
            "list_rule_result": [ComplianceRuleResult.from_dict(_item) for _item in obj.get("listRuleResult")] if obj.get("listRuleResult") is not None else None
        })
        return _obj

ComplianceBreachedOrderInfo.model_rebuild()

