# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, TYPE_CHECKING
from datetime import datetime



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 


class EntityIdentifier(BaseModel):
    """
    Dto to expose mapped keys to new standardised format  # noqa: E501
    """
    identifier_scope:  Optional[StrictStr] = Field(default=None,alias="identifierScope", description="The scope of the identifier") 
    identifier_type:  StrictStr = Field(...,alias="identifierType", description="The type of the identifier") 
    identifier_value:  StrictStr = Field(...,alias="identifierValue", description="The value of the identifier") 
    __properties = ["identifierScope", "identifierType", "identifierValue"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EntityIdentifier:
        """Create an instance of EntityIdentifier from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self. model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if identifier_scope (nullable) is None
        # and model_fields_set contains the field
        if self.identifier_scope is None and "identifier_scope" in self.model_fields_set:
            _dict['identifierScope'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EntityIdentifier:
        """Create an instance of EntityIdentifier from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EntityIdentifier.model_validate(obj)

        _obj = EntityIdentifier.model_validate({
            "identifier_scope": obj.get("identifierScope"),
            "identifier_type": obj.get("identifierType"),
            "identifier_value": obj.get("identifierValue")
        })
        return _obj

EntityIdentifier.model_rebuild()

