# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, ClassVar, TYPE_CHECKING
from datetime import datetime
from uuid import UUID



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 
from finbourne.sdk.services.lusid.models.swing_pricing_decision import SwingPricingDecision


class FundDetails(BaseModel):
    """
    The details of a Fund.  # noqa: E501
    """
    currency:  Optional[StrictStr] = Field(default=None,alias="currency", description="The currency of the fund which is the same as the base currency of all the portfolios of the fund's Abor.") 
    pricing_basis:  Optional[StrictStr] = Field(default=None,alias="pricingBasis", description="The side of the quote the NAV type valued the fund on: Mid, Bid or Ask. Absent when the NAV type defers to the valuation recipe's own pricing basis. When the NAV type has a swing pricing rule this is the basis the rule applied.") 
    swing_pricing: Optional[SwingPricingDecision] = Field(default=None, alias="swingPricing")
    __properties: ClassVar[List[str]] = ["currency", "pricingBasis", "swingPricing"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FundDetails:
        """Create an instance of FundDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, by_alias=True):
        """Returns the dictionary representation of the model"""
        _dict = self. model_dump(by_alias=by_alias,
                          mode='json',
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of swing_pricing
        if self.swing_pricing:
            _dict['swingPricing'] = self.swing_pricing.to_dict(by_alias=by_alias)
        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        # set to None if pricing_basis (nullable) is None
        # and model_fields_set contains the field
        if self.pricing_basis is None and "pricing_basis" in self.model_fields_set:
            _dict['pricingBasis'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FundDetails:
        """Create an instance of FundDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FundDetails.model_validate(obj)

        _obj = FundDetails.model_validate({
            "currency": obj.get("currency"),
            "pricing_basis": obj.get("pricingBasis"),
            "swing_pricing": SwingPricingDecision.from_dict(_v) if (_v := obj.get("swingPricing")) is not None else None
        })
        return _obj

FundDetails.model_rebuild()

