# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, TYPE_CHECKING
from datetime import datetime



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 


class GroupReconciliationUserReviewAdd(BaseModel):
    """
    GroupReconciliationUserReviewAdd
    """
    break_code:  Optional[StrictStr] = Field(default=None,alias="breakCode", description="The break code of the reconciliation result.") 
    match_key:  Optional[StrictStr] = Field(default=None,alias="matchKey", description="The match key of the reconciliation result.") 
    comment_text:  Optional[StrictStr] = Field(default=None,alias="commentText", description="User's comment regarding the reconciliation result.") 
    __properties = ["breakCode", "matchKey", "commentText"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GroupReconciliationUserReviewAdd:
        """Create an instance of GroupReconciliationUserReviewAdd from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self. model_dump(by_alias=True,
                          mode='json',
                          exclude={
                          },
                          exclude_none=True)
        # set to None if break_code (nullable) is None
        # and model_fields_set contains the field
        if self.break_code is None and "break_code" in self.model_fields_set:
            _dict['breakCode'] = None

        # set to None if match_key (nullable) is None
        # and model_fields_set contains the field
        if self.match_key is None and "match_key" in self.model_fields_set:
            _dict['matchKey'] = None

        # set to None if comment_text (nullable) is None
        # and model_fields_set contains the field
        if self.comment_text is None and "comment_text" in self.model_fields_set:
            _dict['commentText'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GroupReconciliationUserReviewAdd:
        """Create an instance of GroupReconciliationUserReviewAdd from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GroupReconciliationUserReviewAdd.model_validate(obj)

        _obj = GroupReconciliationUserReviewAdd.model_validate({
            "break_code": obj.get("breakCode"),
            "match_key": obj.get("matchKey"),
            "comment_text": obj.get("commentText")
        })
        return _obj

GroupReconciliationUserReviewAdd.model_rebuild()

