# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, TYPE_CHECKING
from datetime import datetime



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 
from finbourne.sdk.services.lusid.models.comparison_attribute_value_pair import ComparisonAttributeValuePair


class GroupReconciliationAggregateAttributeValues(BaseModel):
    """
    GroupReconciliationAggregateAttributeValues
    """
    left_aggregate_attributes: List[ComparisonAttributeValuePair] = Field(description="Aggregate attribute names and values for the left hand entity being reconciled.", alias="leftAggregateAttributes")
    right_aggregate_attributes: List[ComparisonAttributeValuePair] = Field(description="Aggregate attribute names and values for the right hand entity being reconciled.", alias="rightAggregateAttributes")
    __properties = ["leftAggregateAttributes", "rightAggregateAttributes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GroupReconciliationAggregateAttributeValues:
        """Create an instance of GroupReconciliationAggregateAttributeValues from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self. model_dump(by_alias=True,
                          mode='json',
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in left_aggregate_attributes (list)
        _items = []
        if self.left_aggregate_attributes:
            for _item in self.left_aggregate_attributes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['leftAggregateAttributes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in right_aggregate_attributes (list)
        _items = []
        if self.right_aggregate_attributes:
            for _item in self.right_aggregate_attributes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['rightAggregateAttributes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GroupReconciliationAggregateAttributeValues:
        """Create an instance of GroupReconciliationAggregateAttributeValues from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GroupReconciliationAggregateAttributeValues.model_validate(obj)

        _obj = GroupReconciliationAggregateAttributeValues.model_validate({
            "left_aggregate_attributes": [ComparisonAttributeValuePair.from_dict(_item) for _item in obj.get("leftAggregateAttributes")] if obj.get("leftAggregateAttributes") is not None else None,
            "right_aggregate_attributes": [ComparisonAttributeValuePair.from_dict(_item) for _item in obj.get("rightAggregateAttributes")] if obj.get("rightAggregateAttributes") is not None else None
        })
        return _obj

GroupReconciliationAggregateAttributeValues.model_rebuild()

