# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, TYPE_CHECKING
from datetime import datetime



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 
from finbourne.sdk.services.lusid.models.grouped_result_of_address_key import GroupedResultOfAddressKey


class VirtualDocumentRow(BaseModel):
    """
    Rows identified by the composite id, based on the data maps  # noqa: E501
    """
    row_id: Optional[Dict[str, Optional[StrictStr]]] = Field(default=None, description="The identifier for the row. This is keyed by address keys, and values obtained through applying the data map to the documents.", alias="rowId")
    row_data: Optional[GroupedResultOfAddressKey] = Field(default=None, alias="rowData")
    __properties = ["rowId", "rowData"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VirtualDocumentRow:
        """Create an instance of VirtualDocumentRow from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self. model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of row_data
        if self.row_data:
            _dict['rowData'] = self.row_data.to_dict()
        # set to None if row_id (nullable) is None
        # and model_fields_set contains the field
        if self.row_id is None and "row_id" in self.model_fields_set:
            _dict['rowId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VirtualDocumentRow:
        """Create an instance of VirtualDocumentRow from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VirtualDocumentRow.model_validate(obj)

        _obj = VirtualDocumentRow.model_validate({
            "row_id": obj.get("rowId"),
            "row_data": GroupedResultOfAddressKey.from_dict(obj.get("rowData")) if obj.get("rowData") is not None else None
        })
        return _obj

VirtualDocumentRow.model_rebuild()

