# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, TYPE_CHECKING
from datetime import datetime



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 
from finbourne.sdk.services.lusid.models.weighted_instrument import WeightedInstrument


class WeightedInstruments(BaseModel):
    """
    Class that models a set of instruments of which each has some quantity and can be identified by a unique label.  # noqa: E501
    """
    instruments: List[WeightedInstrument] = Field(description="The instruments that are held in the set.")
    __properties = ["instruments"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WeightedInstruments:
        """Create an instance of WeightedInstruments from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self. model_dump(by_alias=True,
                          mode='json',
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in instruments (list)
        _items = []
        if self.instruments:
            for _item in self.instruments:
                if _item:
                    _items.append(_item.to_dict())
            _dict['instruments'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WeightedInstruments:
        """Create an instance of WeightedInstruments from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WeightedInstruments.model_validate(obj)

        _obj = WeightedInstruments.model_validate({
            "instruments": [WeightedInstrument.from_dict(_item) for _item in obj.get("instruments")] if obj.get("instruments") is not None else None
        })
        return _obj

WeightedInstruments.model_rebuild()

