# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, TYPE_CHECKING
from datetime import datetime



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 
from finbourne.sdk.services.identity.models.password_policy_response_conditions import PasswordPolicyResponseConditions


class PasswordPolicyResponse(BaseModel):
    """
    PasswordPolicyResponse
    """
    conditions: PasswordPolicyResponseConditions
    __properties = ["conditions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PasswordPolicyResponse:
        """Create an instance of PasswordPolicyResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self. model_dump(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of conditions
        if self.conditions:
            _dict['conditions'] = self.conditions.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PasswordPolicyResponse:
        """Create an instance of PasswordPolicyResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PasswordPolicyResponse.model_validate(obj)

        _obj = PasswordPolicyResponse.model_validate({
            "conditions": PasswordPolicyResponseConditions.from_dict(obj.get("conditions")) if obj.get("conditions") is not None else None
        })
        return _obj

PasswordPolicyResponse.model_rebuild()

