# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, ClassVar, TYPE_CHECKING
from datetime import datetime
from uuid import UUID



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 
from finbourne.sdk.services.insights.models.link import Link


class QueriedRequestLog(BaseModel):
    """
    Holds logged information about a request performed on an API, where only a subset of fields may be populated depending on which fields were requested via the QueryRequestLogs endpoint.  # noqa: E501
    """
    timestamp: datetime = Field(description="The timestamp of the request.")
    id:  StrictStr = Field(...,alias="id", description="The identifier of the request.") 
    application:  StrictStr = Field(...,alias="application", description="The name of the application that the request was made to.") 
    operation:  StrictStr = Field(...,alias="operation", description="The API operation invoked by the request.") 
    session_id:  Optional[StrictStr] = Field(default=None,alias="sessionId", description="The identifier of the session that the request was made in.") 
    verb:  Optional[StrictStr] = Field(default=None,alias="verb", description="The HTTP verb of the request.") 
    url:  Optional[StrictStr] = Field(default=None,alias="url", description="The URL of the request.") 
    domain:  Optional[StrictStr] = Field(default=None,alias="domain", description="The domain of the request.") 
    user:  Optional[StrictStr] = Field(default=None,alias="user", description="The user who made the request.") 
    user_type:  Optional[StrictStr] = Field(default=None,alias="userType", description="The type of the user who made the request.") 
    outcome:  Optional[StrictStr] = Field(default=None,alias="outcome", description="The outcome of the request: Completed, Errored or Failed.") 
    duration: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The duration of the request in milliseconds.")
    http_status_code: Optional[StrictInt] = Field(default=None, description="The status code of the request.", alias="httpStatusCode")
    error_code:  Optional[StrictStr] = Field(default=None,alias="errorCode", description="Error code, if the request had a failure or error.") 
    sdk_language:  Optional[StrictStr] = Field(default=None,alias="sdkLanguage", description="The language of the SDK used.") 
    sdk_version:  Optional[StrictStr] = Field(default=None,alias="sdkVersion", description="The version of the SDK used.") 
    source_application:  Optional[StrictStr] = Field(default=None,alias="sourceApplication", description="The name of the application that made the request.") 
    correlation_id: Optional[List[StrictStr]] = Field(default=None, description="The chain of requestIds preceding this request", alias="correlationId")
    impersonating_user:  Optional[StrictStr] = Field(default=None,alias="impersonatingUser", description="The impersonating user. Only present if the request is an impersonated one") 
    links: Optional[List[Link]] = None
    __properties: ClassVar[List[str]] = ["timestamp", "id", "application", "operation", "sessionId", "verb", "url", "domain", "user", "userType", "outcome", "duration", "httpStatusCode", "errorCode", "sdkLanguage", "sdkVersion", "sourceApplication", "correlationId", "impersonatingUser", "links"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> QueriedRequestLog:
        """Create an instance of QueriedRequestLog from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, by_alias=True):
        """Returns the dictionary representation of the model"""
        _dict = self. model_dump(by_alias=by_alias,
                          mode='json',
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item in self.links:
                if _item:
                    _items.append(_item.to_dict(by_alias=by_alias))
            _dict['links'] = _items
        # set to None if session_id (nullable) is None
        # and model_fields_set contains the field
        if self.session_id is None and "session_id" in self.model_fields_set:
            _dict['sessionId'] = None

        # set to None if verb (nullable) is None
        # and model_fields_set contains the field
        if self.verb is None and "verb" in self.model_fields_set:
            _dict['verb'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        # set to None if domain (nullable) is None
        # and model_fields_set contains the field
        if self.domain is None and "domain" in self.model_fields_set:
            _dict['domain'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        # set to None if user_type (nullable) is None
        # and model_fields_set contains the field
        if self.user_type is None and "user_type" in self.model_fields_set:
            _dict['userType'] = None

        # set to None if outcome (nullable) is None
        # and model_fields_set contains the field
        if self.outcome is None and "outcome" in self.model_fields_set:
            _dict['outcome'] = None

        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict['duration'] = None

        # set to None if http_status_code (nullable) is None
        # and model_fields_set contains the field
        if self.http_status_code is None and "http_status_code" in self.model_fields_set:
            _dict['httpStatusCode'] = None

        # set to None if error_code (nullable) is None
        # and model_fields_set contains the field
        if self.error_code is None and "error_code" in self.model_fields_set:
            _dict['errorCode'] = None

        # set to None if sdk_language (nullable) is None
        # and model_fields_set contains the field
        if self.sdk_language is None and "sdk_language" in self.model_fields_set:
            _dict['sdkLanguage'] = None

        # set to None if sdk_version (nullable) is None
        # and model_fields_set contains the field
        if self.sdk_version is None and "sdk_version" in self.model_fields_set:
            _dict['sdkVersion'] = None

        # set to None if source_application (nullable) is None
        # and model_fields_set contains the field
        if self.source_application is None and "source_application" in self.model_fields_set:
            _dict['sourceApplication'] = None

        # set to None if correlation_id (nullable) is None
        # and model_fields_set contains the field
        if self.correlation_id is None and "correlation_id" in self.model_fields_set:
            _dict['correlationId'] = None

        # set to None if impersonating_user (nullable) is None
        # and model_fields_set contains the field
        if self.impersonating_user is None and "impersonating_user" in self.model_fields_set:
            _dict['impersonatingUser'] = None

        # set to None if links (nullable) is None
        # and model_fields_set contains the field
        if self.links is None and "links" in self.model_fields_set:
            _dict['links'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> QueriedRequestLog:
        """Create an instance of QueriedRequestLog from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return QueriedRequestLog.model_validate(obj)

        _obj = QueriedRequestLog.model_validate({
            "timestamp": obj.get("timestamp"),
            "id": obj.get("id"),
            "application": obj.get("application"),
            "operation": obj.get("operation"),
            "session_id": obj.get("sessionId"),
            "verb": obj.get("verb"),
            "url": obj.get("url"),
            "domain": obj.get("domain"),
            "user": obj.get("user"),
            "user_type": obj.get("userType"),
            "outcome": obj.get("outcome"),
            "duration": obj.get("duration"),
            "http_status_code": obj.get("httpStatusCode"),
            "error_code": obj.get("errorCode"),
            "sdk_language": obj.get("sdkLanguage"),
            "sdk_version": obj.get("sdkVersion"),
            "source_application": obj.get("sourceApplication"),
            "correlation_id": obj.get("correlationId"),
            "impersonating_user": obj.get("impersonatingUser"),
            "links": [Link.from_dict(_item) for _item in _v] if (_v := obj.get("links")) is not None else None
        })
        return _obj

QueriedRequestLog.model_rebuild()

