# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import re  # noqa: F401
import io
import warnings

from pydantic import validate_call, ValidationError, Field, StrictStr
from typing import overload, Optional, Union, Awaitable
from typing_extensions import Annotated

import finbourne.sdk.services.workflow.models as packageModels
from datetime import datetime
from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from uuid import UUID
from finbourne.sdk.services.workflow.models.create_worker_request import CreateWorkerRequest
from finbourne.sdk.services.workflow.models.deleted_entity_response import DeletedEntityResponse
from finbourne.sdk.services.workflow.models.get_worker_result_response import GetWorkerResultResponse
from finbourne.sdk.services.workflow.models.paged_resource_list_of_worker import PagedResourceListOfWorker
from finbourne.sdk.services.workflow.models.run_worker_request import RunWorkerRequest
from finbourne.sdk.services.workflow.models.run_worker_response import RunWorkerResponse
from finbourne.sdk.services.workflow.models.update_worker_request import UpdateWorkerRequest
from finbourne.sdk.services.workflow.models.worker import Worker
from finbourne.sdk.api_client import ApiClient
from finbourne.sdk.api_response import ApiResponse
from finbourne.sdk.extensions.api_client import SyncApiClient
from finbourne.sdk.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)
from finbourne.sdk.extensions.configuration_options import ConfigurationOptions

class WorkersApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client = None, sync_api_client = None) -> None:
        if sync_api_client is not None:
            self.sync_api_client = sync_api_client
        elif api_client is not None:
            self.api_client = api_client
        else:
            self.api_client = ApiClient.get_default()

    @validate_call
    def create_worker(self, create_worker_request: CreateWorkerRequest, **kwargs) -> Worker:
        """CreateWorker: Create a new Worker  # noqa: E501

        If the Worker already exists a failure will be returned  # noqa: E501
        :param create_worker_request: Worker to be created (required)
        :type create_worker_request: CreateWorkerRequest
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: Worker
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the create_worker_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.create_worker_with_http_info(create_worker_request, **kwargs)  # noqa: E501

    @validate_call
    def create_worker_with_http_info(self, create_worker_request: CreateWorkerRequest, **kwargs) -> ApiResponse[Worker]:
        """CreateWorker: Create a new Worker  # noqa: E501

        If the Worker already exists a failure will be returned  # noqa: E501
        :param create_worker_request: Worker to be created (required)
        :type create_worker_request: CreateWorkerRequest
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(Worker, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'create_worker_request'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_worker" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['create_worker_request'] is not None:
            _body_params = _params['create_worker_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.sync_api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '201': "Worker",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/workflow/api/workers', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def delete_worker(self, scope: StrictStr, code: StrictStr, **kwargs) -> DeletedEntityResponse:
        """DeleteWorker: Delete a Worker  # noqa: E501

        If the Worker does not exist a failure will be returned  # noqa: E501
        :param scope: Scope of the worker to be deleted (required)
        :type scope: str
        :param code: Code of the worker to be deleted (required)
        :type code: str
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: DeletedEntityResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the delete_worker_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.delete_worker_with_http_info(scope, code, **kwargs)  # noqa: E501

    @validate_call
    def delete_worker_with_http_info(self, scope: StrictStr, code: StrictStr, **kwargs) -> ApiResponse[DeletedEntityResponse]:
        """DeleteWorker: Delete a Worker  # noqa: E501

        If the Worker does not exist a failure will be returned  # noqa: E501
        :param scope: Scope of the worker to be deleted (required)
        :type scope: str
        :param code: Code of the worker to be deleted (required)
        :type code: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(DeletedEntityResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_worker" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "DeletedEntityResponse",
            '400': "LusidValidationProblemDetails",
            '404': "str",
        }

        return self.sync_api_client.call_api(
            '/workflow/api/workers/{scope}/{code}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def get_worker(self, scope: StrictStr, code: StrictStr, as_at: Optional[datetime] = None, **kwargs) -> Worker:
        """GetWorker: Get a Worker  # noqa: E501

        Will return a NotFound failure if the Worker does not exist  # noqa: E501
        :param scope: Scope of the worker (required)
        :type scope: str
        :param code: Code of the worker (required)
        :type code: str
        :param as_at: The asAt datetime at which to retrieve the Worker. Defaults to returning the latest version of the Worker if not specified.
        :type as_at: datetime
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: Worker
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_worker_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.get_worker_with_http_info(scope, code, as_at, **kwargs)  # noqa: E501

    @validate_call
    def get_worker_with_http_info(self, scope: StrictStr, code: StrictStr, as_at: Optional[datetime] = None, **kwargs) -> ApiResponse[Worker]:
        """GetWorker: Get a Worker  # noqa: E501

        Will return a NotFound failure if the Worker does not exist  # noqa: E501
        :param scope: Scope of the worker (required)
        :type scope: str
        :param code: Code of the worker (required)
        :type code: str
        :param as_at: The asAt datetime at which to retrieve the Worker. Defaults to returning the latest version of the Worker if not specified.
        :type as_at: datetime
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(Worker, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'as_at'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_worker" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        if _params.get('as_at') is not None:  # noqa: E501
            if isinstance(_params['as_at'], datetime):
                _query_params.append(('asAt', _params['as_at'].strftime(self.sync_api_client.configuration.datetime_format)))
            else:
                _query_params.append(('asAt', _params['as_at']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "Worker",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/workflow/api/workers/{scope}/{code}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def get_worker_result(self, run_id: StrictStr, **kwargs) -> GetWorkerResultResponse:
        """GetWorkerResult: Get the status of a specific run of a worker with any relevant results  # noqa: E501

        :param run_id: The ID returned when calling Run Worker (required)
        :type run_id: UUID
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: GetWorkerResultResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_worker_result_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.get_worker_result_with_http_info(run_id, **kwargs)  # noqa: E501

    @validate_call
    def get_worker_result_with_http_info(self, run_id: StrictStr, **kwargs) -> ApiResponse[GetWorkerResultResponse]:
        """GetWorkerResult: Get the status of a specific run of a worker with any relevant results  # noqa: E501

        :param run_id: The ID returned when calling Run Worker (required)
        :type run_id: UUID
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(GetWorkerResultResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'run_id'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_worker_result" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['run_id']:
            _path_params['runId'] = _params['run_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "GetWorkerResultResponse",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/workflow/api/workers/{runId}/$result', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def list_workers(self, as_at: Optional[datetime] = None, filter: Optional[StrictStr] = None, sort_by: Optional[List[str]] = None, limit: Optional[int] = None, page: Optional[StrictStr] = None, **kwargs) -> PagedResourceListOfWorker:
        """ListWorkers: List Workers  # noqa: E501

        :param as_at: The asAt datetime at which to list the Workers. Defaults to return the latest version of each Worker if not specified.
        :type as_at: datetime
        :param filter: Expression to filter the result set. Read more about filtering results from LUSID here: https://support.lusid.com/filtering-results-from-lusid.
        :type filter: str
        :param sort_by: A list of field names or properties to sort by, each optionally suffixed by \" ASC\" or \" DESC\"
        :type sort_by: List[str]
        :param limit: When paginating, limit the number of returned results to this many.
        :type limit: int
        :param page: The pagination token to use to continue listing workers from a previous call to list workers. This value is returned from the previous call. If a pagination token is provided the sortBy, filter, effectiveAt, and asAt fields must not have changed since the original request.
        :type page: str
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: PagedResourceListOfWorker
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_workers_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.list_workers_with_http_info(as_at, filter, sort_by, limit, page, **kwargs)  # noqa: E501

    @validate_call
    def list_workers_with_http_info(self, as_at: Optional[datetime] = None, filter: Optional[StrictStr] = None, sort_by: Optional[List[str]] = None, limit: Optional[int] = None, page: Optional[StrictStr] = None, **kwargs) -> ApiResponse[PagedResourceListOfWorker]:
        """ListWorkers: List Workers  # noqa: E501

        :param as_at: The asAt datetime at which to list the Workers. Defaults to return the latest version of each Worker if not specified.
        :type as_at: datetime
        :param filter: Expression to filter the result set. Read more about filtering results from LUSID here: https://support.lusid.com/filtering-results-from-lusid.
        :type filter: str
        :param sort_by: A list of field names or properties to sort by, each optionally suffixed by \" ASC\" or \" DESC\"
        :type sort_by: List[str]
        :param limit: When paginating, limit the number of returned results to this many.
        :type limit: int
        :param page: The pagination token to use to continue listing workers from a previous call to list workers. This value is returned from the previous call. If a pagination token is provided the sortBy, filter, effectiveAt, and asAt fields must not have changed since the original request.
        :type page: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(PagedResourceListOfWorker, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'as_at',
            'filter',
            'sort_by',
            'limit',
            'page'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_workers" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('as_at') is not None:  # noqa: E501
            if isinstance(_params['as_at'], datetime):
                _query_params.append(('asAt', _params['as_at'].strftime(self.sync_api_client.configuration.datetime_format)))
            else:
                _query_params.append(('asAt', _params['as_at']))

        if _params.get('filter') is not None:  # noqa: E501
            _query_params.append(('filter', _params['filter']))

        if _params.get('sort_by') is not None:  # noqa: E501
            _query_params.append(('sortBy', _params['sort_by']))
            _collection_formats['sortBy'] = 'multi'

        if _params.get('limit') is not None:  # noqa: E501
            _query_params.append(('limit', _params['limit']))

        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "PagedResourceListOfWorker",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/workflow/api/workers', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def run_worker(self, scope: StrictStr, code: StrictStr, run_worker_request: RunWorkerRequest, as_at: Optional[datetime] = None, **kwargs) -> RunWorkerResponse:
        """RunWorker: Run a Worker  # noqa: E501

        :param scope: Scope of the worker (required)
        :type scope: str
        :param code: Code of the worker (required)
        :type code: str
        :param run_worker_request:  (required)
        :type run_worker_request: RunWorkerRequest
        :param as_at: The asAt datetime at which to retrieve the Worker. Defaults to returning the latest version of the Worker if not specified.
        :type as_at: datetime
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: RunWorkerResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the run_worker_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.run_worker_with_http_info(scope, code, run_worker_request, as_at, **kwargs)  # noqa: E501

    @validate_call
    def run_worker_with_http_info(self, scope: StrictStr, code: StrictStr, run_worker_request: RunWorkerRequest, as_at: Optional[datetime] = None, **kwargs) -> ApiResponse[RunWorkerResponse]:
        """RunWorker: Run a Worker  # noqa: E501

        :param scope: Scope of the worker (required)
        :type scope: str
        :param code: Code of the worker (required)
        :type code: str
        :param run_worker_request:  (required)
        :type run_worker_request: RunWorkerRequest
        :param as_at: The asAt datetime at which to retrieve the Worker. Defaults to returning the latest version of the Worker if not specified.
        :type as_at: datetime
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(RunWorkerResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'run_worker_request',
            'as_at'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method run_worker" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        if _params.get('as_at') is not None:  # noqa: E501
            if isinstance(_params['as_at'], datetime):
                _query_params.append(('asAt', _params['as_at'].strftime(self.sync_api_client.configuration.datetime_format)))
            else:
                _query_params.append(('asAt', _params['as_at']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['run_worker_request'] is not None:
            _body_params = _params['run_worker_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.sync_api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "RunWorkerResponse",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/workflow/api/workers/{scope}/{code}/$run', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def update_worker(self, scope: StrictStr, code: StrictStr, update_worker_request: UpdateWorkerRequest, **kwargs) -> Worker:
        """UpdateWorker: Update a Worker  # noqa: E501

        If the Worker does not exist a failure will be returned  # noqa: E501
        :param scope: Scope of the worker to be updated (required)
        :type scope: str
        :param code: Code of the worker to be updated (required)
        :type code: str
        :param update_worker_request: State of the updated worker (required)
        :type update_worker_request: UpdateWorkerRequest
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: Worker
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the update_worker_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.update_worker_with_http_info(scope, code, update_worker_request, **kwargs)  # noqa: E501

    @validate_call
    def update_worker_with_http_info(self, scope: StrictStr, code: StrictStr, update_worker_request: UpdateWorkerRequest, **kwargs) -> ApiResponse[Worker]:
        """UpdateWorker: Update a Worker  # noqa: E501

        If the Worker does not exist a failure will be returned  # noqa: E501
        :param scope: Scope of the worker to be updated (required)
        :type scope: str
        :param code: Code of the worker to be updated (required)
        :type code: str
        :param update_worker_request: State of the updated worker (required)
        :type update_worker_request: UpdateWorkerRequest
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(Worker, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'update_worker_request'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_worker" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['update_worker_request'] is not None:
            _body_params = _params['update_worker_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.sync_api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "Worker",
            '400': "LusidValidationProblemDetails",
            '404': "str",
        }

        return self.sync_api_client.call_api(
            '/workflow/api/workers/{scope}/{code}', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)


  # --- ASYNC API METHODS ---


    @validate_call
    async def create_worker_async(self, create_worker_request: CreateWorkerRequest, **kwargs) -> Worker:
            """CreateWorker: Create a new Worker  # noqa: E501
            If the Worker already exists a failure will be returned  # noqa: E501
            
            :param create_worker_request: Worker to be created (required)
            :type create_worker_request: CreateWorkerRequest
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: Worker
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the create_worker_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.create_worker_with_http_info_async(create_worker_request, **kwargs)  # noqa: E501

    @validate_call
    async def create_worker_with_http_info_async(self, create_worker_request: CreateWorkerRequest, **kwargs) -> ApiResponse[Worker]:
            """CreateWorker: Create a new Worker  # noqa: E501

            If the Worker already exists a failure will be returned  # noqa: E501

            :param create_worker_request: Worker to be created (required)
            :type create_worker_request: CreateWorkerRequest
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(Worker, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'create_worker_request'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method create_worker" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}

            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            if _params['create_worker_request'] is not None:
                _body_params = _params['create_worker_request']

            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # set the HTTP header `Content-Type`
            _content_types_list = _params.get('_content_type',
                self.api_client.select_header_content_type(
                    ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
            if _content_types_list:
                    _header_params['Content-Type'] = _content_types_list

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '201': "Worker",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/workflow/api/workers', 'POST',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def delete_worker_async(self, scope: StrictStr, code: StrictStr, **kwargs) -> DeletedEntityResponse:
            """DeleteWorker: Delete a Worker  # noqa: E501
            If the Worker does not exist a failure will be returned  # noqa: E501
            
            :param scope: Scope of the worker to be deleted (required)
            :type scope: str
            :param code: Code of the worker to be deleted (required)
            :type code: str
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: DeletedEntityResponse
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the delete_worker_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.delete_worker_with_http_info_async(scope, code, **kwargs)  # noqa: E501

    @validate_call
    async def delete_worker_with_http_info_async(self, scope: StrictStr, code: StrictStr, **kwargs) -> ApiResponse[DeletedEntityResponse]:
            """DeleteWorker: Delete a Worker  # noqa: E501

            If the Worker does not exist a failure will be returned  # noqa: E501

            :param scope: Scope of the worker to be deleted (required)
            :type scope: str
            :param code: Code of the worker to be deleted (required)
            :type code: str
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(DeletedEntityResponse, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'code'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method delete_worker" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']


            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "DeletedEntityResponse",
                '400': "LusidValidationProblemDetails",
                '404': "str",
            }

            return await self.api_client.call_api_async(
                '/workflow/api/workers/{scope}/{code}', 'DELETE',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def get_worker_async(self, scope: StrictStr, code: StrictStr, as_at: Optional[datetime] = None, **kwargs) -> Worker:
            """GetWorker: Get a Worker  # noqa: E501
            Will return a NotFound failure if the Worker does not exist  # noqa: E501
            
            :param scope: Scope of the worker (required)
            :type scope: str
            :param code: Code of the worker (required)
            :type code: str
            :param as_at: The asAt datetime at which to retrieve the Worker. Defaults to returning the latest version of the Worker if not specified.
            :type as_at: datetime
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: Worker
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the get_worker_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.get_worker_with_http_info_async(scope, code, as_at, **kwargs)  # noqa: E501

    @validate_call
    async def get_worker_with_http_info_async(self, scope: StrictStr, code: StrictStr, as_at: Optional[datetime] = None, **kwargs) -> ApiResponse[Worker]:
            """GetWorker: Get a Worker  # noqa: E501

            Will return a NotFound failure if the Worker does not exist  # noqa: E501

            :param scope: Scope of the worker (required)
            :type scope: str
            :param code: Code of the worker (required)
            :type code: str
            :param as_at: The asAt datetime at which to retrieve the Worker. Defaults to returning the latest version of the Worker if not specified.
            :type as_at: datetime
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(Worker, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'code',
                'as_at'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method get_worker" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']


            # process the query parameters
            _query_params = []
            if _params.get('as_at') is not None:  # noqa: E501
                if isinstance(_params['as_at'], datetime):
                    _query_params.append(('asAt', _params['as_at'].strftime(self.api_client.configuration.datetime_format)))
                else:
                    _query_params.append(('asAt', _params['as_at']))

            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "Worker",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/workflow/api/workers/{scope}/{code}', 'GET',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def get_worker_result_async(self, run_id: StrictStr, **kwargs) -> GetWorkerResultResponse:
            """GetWorkerResult: Get the status of a specific run of a worker with any relevant results  # noqa: E501
            
            :param run_id: The ID returned when calling Run Worker (required)
            :type run_id: UUID
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: GetWorkerResultResponse
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the get_worker_result_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.get_worker_result_with_http_info_async(run_id, **kwargs)  # noqa: E501

    @validate_call
    async def get_worker_result_with_http_info_async(self, run_id: StrictStr, **kwargs) -> ApiResponse[GetWorkerResultResponse]:
            """GetWorkerResult: Get the status of a specific run of a worker with any relevant results  # noqa: E501


            :param run_id: The ID returned when calling Run Worker (required)
            :type run_id: UUID
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(GetWorkerResultResponse, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'run_id'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method get_worker_result" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['run_id']:
                _path_params['runId'] = _params['run_id']


            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "GetWorkerResultResponse",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/workflow/api/workers/{runId}/$result', 'GET',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def list_workers_async(self, as_at: Optional[datetime] = None, filter: Optional[StrictStr] = None, sort_by: Optional[List[str]] = None, limit: Optional[int] = None, page: Optional[StrictStr] = None, **kwargs) -> PagedResourceListOfWorker:
            """ListWorkers: List Workers  # noqa: E501
            
            :param as_at: The asAt datetime at which to list the Workers. Defaults to return the latest version of each Worker if not specified.
            :type as_at: datetime
            :param filter: Expression to filter the result set. Read more about filtering results from LUSID here: https://support.lusid.com/filtering-results-from-lusid.
            :type filter: str
            :param sort_by: A list of field names or properties to sort by, each optionally suffixed by \" ASC\" or \" DESC\"
            :type sort_by: List[str]
            :param limit: When paginating, limit the number of returned results to this many.
            :type limit: int
            :param page: The pagination token to use to continue listing workers from a previous call to list workers. This value is returned from the previous call. If a pagination token is provided the sortBy, filter, effectiveAt, and asAt fields must not have changed since the original request.
            :type page: str
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: PagedResourceListOfWorker
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the list_workers_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.list_workers_with_http_info_async(as_at, filter, sort_by, limit, page, **kwargs)  # noqa: E501

    @validate_call
    async def list_workers_with_http_info_async(self, as_at: Optional[datetime] = None, filter: Optional[StrictStr] = None, sort_by: Optional[List[str]] = None, limit: Optional[int] = None, page: Optional[StrictStr] = None, **kwargs) -> ApiResponse[PagedResourceListOfWorker]:
            """ListWorkers: List Workers  # noqa: E501


            :param as_at: The asAt datetime at which to list the Workers. Defaults to return the latest version of each Worker if not specified.
            :type as_at: datetime
            :param filter: Expression to filter the result set. Read more about filtering results from LUSID here: https://support.lusid.com/filtering-results-from-lusid.
            :type filter: str
            :param sort_by: A list of field names or properties to sort by, each optionally suffixed by \" ASC\" or \" DESC\"
            :type sort_by: List[str]
            :param limit: When paginating, limit the number of returned results to this many.
            :type limit: int
            :param page: The pagination token to use to continue listing workers from a previous call to list workers. This value is returned from the previous call. If a pagination token is provided the sortBy, filter, effectiveAt, and asAt fields must not have changed since the original request.
            :type page: str
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(PagedResourceListOfWorker, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'as_at',
                'filter',
                'sort_by',
                'limit',
                'page'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method list_workers" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}

            # process the query parameters
            _query_params = []
            if _params.get('as_at') is not None:  # noqa: E501
                if isinstance(_params['as_at'], datetime):
                    _query_params.append(('asAt', _params['as_at'].strftime(self.api_client.configuration.datetime_format)))
                else:
                    _query_params.append(('asAt', _params['as_at']))

            if _params.get('filter') is not None:  # noqa: E501
                _query_params.append(('filter', _params['filter']))

            if _params.get('sort_by') is not None:  # noqa: E501
                _query_params.append(('sortBy', _params['sort_by']))
                _collection_formats['sortBy'] = 'multi'

            if _params.get('limit') is not None:  # noqa: E501
                _query_params.append(('limit', _params['limit']))

            if _params.get('page') is not None:  # noqa: E501
                _query_params.append(('page', _params['page']))

            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "PagedResourceListOfWorker",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/workflow/api/workers', 'GET',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def run_worker_async(self, scope: StrictStr, code: StrictStr, run_worker_request: RunWorkerRequest, as_at: Optional[datetime] = None, **kwargs) -> RunWorkerResponse:
            """RunWorker: Run a Worker  # noqa: E501
            
            :param scope: Scope of the worker (required)
            :type scope: str
            :param code: Code of the worker (required)
            :type code: str
            :param run_worker_request:  (required)
            :type run_worker_request: RunWorkerRequest
            :param as_at: The asAt datetime at which to retrieve the Worker. Defaults to returning the latest version of the Worker if not specified.
            :type as_at: datetime
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: RunWorkerResponse
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the run_worker_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.run_worker_with_http_info_async(scope, code, run_worker_request, as_at, **kwargs)  # noqa: E501

    @validate_call
    async def run_worker_with_http_info_async(self, scope: StrictStr, code: StrictStr, run_worker_request: RunWorkerRequest, as_at: Optional[datetime] = None, **kwargs) -> ApiResponse[RunWorkerResponse]:
            """RunWorker: Run a Worker  # noqa: E501


            :param scope: Scope of the worker (required)
            :type scope: str
            :param code: Code of the worker (required)
            :type code: str
            :param run_worker_request:  (required)
            :type run_worker_request: RunWorkerRequest
            :param as_at: The asAt datetime at which to retrieve the Worker. Defaults to returning the latest version of the Worker if not specified.
            :type as_at: datetime
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(RunWorkerResponse, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'code',
                'run_worker_request',
                'as_at'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method run_worker" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']


            # process the query parameters
            _query_params = []
            if _params.get('as_at') is not None:  # noqa: E501
                if isinstance(_params['as_at'], datetime):
                    _query_params.append(('asAt', _params['as_at'].strftime(self.api_client.configuration.datetime_format)))
                else:
                    _query_params.append(('asAt', _params['as_at']))

            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            if _params['run_worker_request'] is not None:
                _body_params = _params['run_worker_request']

            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # set the HTTP header `Content-Type`
            _content_types_list = _params.get('_content_type',
                self.api_client.select_header_content_type(
                    ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
            if _content_types_list:
                    _header_params['Content-Type'] = _content_types_list

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "RunWorkerResponse",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/workflow/api/workers/{scope}/{code}/$run', 'POST',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def update_worker_async(self, scope: StrictStr, code: StrictStr, update_worker_request: UpdateWorkerRequest, **kwargs) -> Worker:
            """UpdateWorker: Update a Worker  # noqa: E501
            If the Worker does not exist a failure will be returned  # noqa: E501
            
            :param scope: Scope of the worker to be updated (required)
            :type scope: str
            :param code: Code of the worker to be updated (required)
            :type code: str
            :param update_worker_request: State of the updated worker (required)
            :type update_worker_request: UpdateWorkerRequest
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: Worker
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the update_worker_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.update_worker_with_http_info_async(scope, code, update_worker_request, **kwargs)  # noqa: E501

    @validate_call
    async def update_worker_with_http_info_async(self, scope: StrictStr, code: StrictStr, update_worker_request: UpdateWorkerRequest, **kwargs) -> ApiResponse[Worker]:
            """UpdateWorker: Update a Worker  # noqa: E501

            If the Worker does not exist a failure will be returned  # noqa: E501

            :param scope: Scope of the worker to be updated (required)
            :type scope: str
            :param code: Code of the worker to be updated (required)
            :type code: str
            :param update_worker_request: State of the updated worker (required)
            :type update_worker_request: UpdateWorkerRequest
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(Worker, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'code',
                'update_worker_request'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method update_worker" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']


            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            if _params['update_worker_request'] is not None:
                _body_params = _params['update_worker_request']

            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # set the HTTP header `Content-Type`
            _content_types_list = _params.get('_content_type',
                self.api_client.select_header_content_type(
                    ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
            if _content_types_list:
                    _header_params['Content-Type'] = _content_types_list

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "Worker",
                '400': "LusidValidationProblemDetails",
                '404': "str",
            }

            return await self.api_client.call_api_async(
                '/workflow/api/workers/{scope}/{code}', 'PUT',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)



