# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, ClassVar, TYPE_CHECKING
from datetime import datetime
from uuid import UUID



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 
from finbourne.sdk.services.workflow.models.action_definition_response import ActionDefinitionResponse
from finbourne.sdk.services.workflow.models.initial_state import InitialState
from finbourne.sdk.services.workflow.models.perpetual_property import PerpetualProperty
from finbourne.sdk.services.workflow.models.resource_id import ResourceId
from finbourne.sdk.services.workflow.models.task_field_definition import TaskFieldDefinition
from finbourne.sdk.services.workflow.models.task_state_definition import TaskStateDefinition
from finbourne.sdk.services.workflow.models.task_transition_definition import TaskTransitionDefinition
from finbourne.sdk.services.workflow.models.transition_trigger_definition import TransitionTriggerDefinition
from finbourne.sdk.services.workflow.models.version_info import VersionInfo


class TaskDefinition(BaseModel):
    """
    Task Definition  # noqa: E501
    """
    id: ResourceId
    version: Optional[VersionInfo] = None
    display_name:  StrictStr = Field(...,alias="displayName", description="Human readable name") 
    description:  Optional[StrictStr] = Field(default=None,alias="description", description="Human readable description") 
    states: List[TaskStateDefinition] = Field(description="The states this Task Definition operates over")
    field_schema: Optional[List[TaskFieldDefinition]] = Field(default=None, description="The Fields that this Task Definition operates on", alias="fieldSchema")
    initial_state: InitialState = Field(alias="initialState")
    triggers: Optional[List[TransitionTriggerDefinition]] = Field(default=None, description="The Triggers for State transition")
    actions: Optional[List[ActionDefinitionResponse]] = Field(default=None, description="The Actions of this Task - executed after a Transition completion")
    transitions: Optional[List[TaskTransitionDefinition]] = Field(default=None, description="The Transitions between States")
    properties: Optional[Dict[str, PerpetualProperty]] = Field(default=None, description="The properties of the Task Definition, keyed by property key. Only populated when set on the request (Create/Update) or when property keys are requested (Get/List).")
    __properties: ClassVar[List[str]] = ["id", "version", "displayName", "description", "states", "fieldSchema", "initialState", "triggers", "actions", "transitions", "properties"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TaskDefinition:
        """Create an instance of TaskDefinition from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self, by_alias=True):
        """Returns the dictionary representation of the model"""
        _dict = self. model_dump(by_alias=by_alias,
                          mode='json',
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of id
        if self.id:
            _dict['id'] = self.id.to_dict(by_alias=by_alias)
        # override the default output from pydantic by calling `to_dict()` of version
        if self.version:
            _dict['version'] = self.version.to_dict(by_alias=by_alias)
        # override the default output from pydantic by calling `to_dict()` of each item in states (list)
        _items = []
        if self.states:
            for _item in self.states:
                if _item:
                    _items.append(_item.to_dict(by_alias=by_alias))
            _dict['states'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in field_schema (list)
        _items = []
        if self.field_schema:
            for _item in self.field_schema:
                if _item:
                    _items.append(_item.to_dict(by_alias=by_alias))
            _dict['fieldSchema'] = _items
        # override the default output from pydantic by calling `to_dict()` of initial_state
        if self.initial_state:
            _dict['initialState'] = self.initial_state.to_dict(by_alias=by_alias)
        # override the default output from pydantic by calling `to_dict()` of each item in triggers (list)
        _items = []
        if self.triggers:
            for _item in self.triggers:
                if _item:
                    _items.append(_item.to_dict(by_alias=by_alias))
            _dict['triggers'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in actions (list)
        _items = []
        if self.actions:
            for _item in self.actions:
                if _item:
                    _items.append(_item.to_dict(by_alias=by_alias))
            _dict['actions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in transitions (list)
        _items = []
        if self.transitions:
            for _item in self.transitions:
                if _item:
                    _items.append(_item.to_dict(by_alias=by_alias))
            _dict['transitions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in properties (dict)
        _field_dict = {}
        if self.properties:
            for _key in self.properties:
                if self.properties[_key]:
                    _field_dict[_key] = self.properties[_key].to_dict(by_alias=by_alias)
            _dict['properties'] = _field_dict
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if field_schema (nullable) is None
        # and model_fields_set contains the field
        if self.field_schema is None and "field_schema" in self.model_fields_set:
            _dict['fieldSchema'] = None

        # set to None if triggers (nullable) is None
        # and model_fields_set contains the field
        if self.triggers is None and "triggers" in self.model_fields_set:
            _dict['triggers'] = None

        # set to None if actions (nullable) is None
        # and model_fields_set contains the field
        if self.actions is None and "actions" in self.model_fields_set:
            _dict['actions'] = None

        # set to None if transitions (nullable) is None
        # and model_fields_set contains the field
        if self.transitions is None and "transitions" in self.model_fields_set:
            _dict['transitions'] = None

        # set to None if properties (nullable) is None
        # and model_fields_set contains the field
        if self.properties is None and "properties" in self.model_fields_set:
            _dict['properties'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TaskDefinition:
        """Create an instance of TaskDefinition from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TaskDefinition.model_validate(obj)

        _obj = TaskDefinition.model_validate({
            "id": ResourceId.from_dict(_v) if (_v := obj.get("id")) is not None else None,
            "version": VersionInfo.from_dict(_v) if (_v := obj.get("version")) is not None else None,
            "display_name": obj.get("displayName"),
            "description": obj.get("description"),
            "states": [TaskStateDefinition.from_dict(_item) for _item in _v] if (_v := obj.get("states")) is not None else None,
            "field_schema": [TaskFieldDefinition.from_dict(_item) for _item in _v] if (_v := obj.get("fieldSchema")) is not None else None,
            "initial_state": InitialState.from_dict(_v) if (_v := obj.get("initialState")) is not None else None,
            "triggers": [TransitionTriggerDefinition.from_dict(_item) for _item in _v] if (_v := obj.get("triggers")) is not None else None,
            "actions": [ActionDefinitionResponse.from_dict(_item) for _item in _v] if (_v := obj.get("actions")) is not None else None,
            "transitions": [TaskTransitionDefinition.from_dict(_item) for _item in _v] if (_v := obj.get("transitions")) is not None else None,
            "properties": dict(
                (_k, PerpetualProperty.from_dict(_v))
                for _k, _v in _val.items()
            )
            if (_val := obj.get("properties")) is not None
            else None
        })
        return _obj

TaskDefinition.model_rebuild()

