# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import re  # noqa: F401
import io
import warnings

from pydantic import validate_call, ValidationError, Field, StrictStr
from typing import overload, Optional, Union, Awaitable
from typing_extensions import Annotated

import finbourne.sdk.services.notifications.models as packageModels
from pydantic import Field, StrictInt, field_validator
from typing import Optional
from typing_extensions import Annotated
from finbourne.sdk.services.notifications.models.create_subscription import CreateSubscription
from finbourne.sdk.services.notifications.models.resource_list_of_subscription import ResourceListOfSubscription
from finbourne.sdk.services.notifications.models.subscription import Subscription
from finbourne.sdk.services.notifications.models.update_subscription import UpdateSubscription
from finbourne.sdk.api_client import ApiClient
from finbourne.sdk.api_response import ApiResponse
from finbourne.sdk.extensions.api_client import SyncApiClient
from finbourne.sdk.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)
from finbourne.sdk.extensions.configuration_options import ConfigurationOptions

class SubscriptionsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client = None, sync_api_client = None) -> None:
        if sync_api_client is not None:
            self.sync_api_client = sync_api_client
        elif api_client is not None:
            self.api_client = api_client
        else:
            self.api_client = ApiClient.get_default()

    @validate_call
    def create_subscription(self, create_subscription: CreateSubscription, **kwargs) -> Subscription:
        """CreateSubscription: Create a new subscription.  # noqa: E501

        :param create_subscription: The data to create a subscription (required)
        :type create_subscription: CreateSubscription
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: Subscription
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the create_subscription_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.create_subscription_with_http_info(create_subscription, **kwargs)  # noqa: E501

    @validate_call
    def create_subscription_with_http_info(self, create_subscription: CreateSubscription, **kwargs) -> ApiResponse[Subscription]:
        """CreateSubscription: Create a new subscription.  # noqa: E501

        :param create_subscription: The data to create a subscription (required)
        :type create_subscription: CreateSubscription
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(Subscription, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'create_subscription'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_subscription" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['create_subscription'] is not None:
            _body_params = _params['create_subscription']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.sync_api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '201': "Subscription",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/notifications/api/subscriptions', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def delete_subscription(self, scope: StrictStr, code: StrictStr, **kwargs) -> None:
        """DeleteSubscription: Delete a subscription.  # noqa: E501

        :param scope: The scope that identifies a subscription (required)
        :type scope: str
        :param code: The code that identifies a subscription (required)
        :type code: str
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the delete_subscription_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.delete_subscription_with_http_info(scope, code, **kwargs)  # noqa: E501

    @validate_call
    def delete_subscription_with_http_info(self, scope: StrictStr, code: StrictStr, **kwargs) -> None:
        """DeleteSubscription: Delete a subscription.  # noqa: E501

        :param scope: The scope that identifies a subscription (required)
        :type scope: str
        :param code: The code that identifies a subscription (required)
        :type code: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: None
        """

        _params = locals()

        _all_params = [
            'scope',
            'code'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_subscription" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {}

        return self.sync_api_client.call_api(
            '/notifications/api/subscriptions/{scope}/{code}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def get_subscription(self, scope: StrictStr, code: StrictStr, **kwargs) -> Subscription:
        """GetSubscription: Get a subscription.  # noqa: E501

        :param scope: The scope that identifies a subscription (required)
        :type scope: str
        :param code: The code that identifies a subscription (required)
        :type code: str
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: Subscription
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_subscription_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.get_subscription_with_http_info(scope, code, **kwargs)  # noqa: E501

    @validate_call
    def get_subscription_with_http_info(self, scope: StrictStr, code: StrictStr, **kwargs) -> ApiResponse[Subscription]:
        """GetSubscription: Get a subscription.  # noqa: E501

        :param scope: The scope that identifies a subscription (required)
        :type scope: str
        :param code: The code that identifies a subscription (required)
        :type code: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(Subscription, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_subscription" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "Subscription",
            '400': "LusidValidationProblemDetails",
            '404': "str",
        }

        return self.sync_api_client.call_api(
            '/notifications/api/subscriptions/{scope}/{code}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def list_subscriptions(self, filter: Optional[StrictStr] = None, sort_by: Optional[StrictStr] = None, page: Optional[StrictStr] = None, limit: Optional[int] = None, **kwargs) -> ResourceListOfSubscription:
        """ListSubscriptions: List subscriptions.  # noqa: E501

        :param filter: Expression to filter the result set. Read more about <a href=\"https://support.lusid.com/filtering-results-from-lusid\"> filtering results from LUSID</a>.
        :type filter: str
        :param sort_by: Fields to order the result set. Read more about <a href=\"https://support.lusid.com/filtering-results-from-lusid\"> filtering results from LUSID</a>
        :type sort_by: str
        :param page: Encoded page string returned from a previous search result that will retrieve the next page of data. When this field is supplied the filter  field should not be supplied.
        :type page: str
        :param limit: The maximum number of subscriptions to retrieve.
        :type limit: int
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: ResourceListOfSubscription
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_subscriptions_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.list_subscriptions_with_http_info(filter, sort_by, page, limit, **kwargs)  # noqa: E501

    @validate_call
    def list_subscriptions_with_http_info(self, filter: Optional[StrictStr] = None, sort_by: Optional[StrictStr] = None, page: Optional[StrictStr] = None, limit: Optional[int] = None, **kwargs) -> ApiResponse[ResourceListOfSubscription]:
        """ListSubscriptions: List subscriptions.  # noqa: E501

        :param filter: Expression to filter the result set. Read more about <a href=\"https://support.lusid.com/filtering-results-from-lusid\"> filtering results from LUSID</a>.
        :type filter: str
        :param sort_by: Fields to order the result set. Read more about <a href=\"https://support.lusid.com/filtering-results-from-lusid\"> filtering results from LUSID</a>
        :type sort_by: str
        :param page: Encoded page string returned from a previous search result that will retrieve the next page of data. When this field is supplied the filter  field should not be supplied.
        :type page: str
        :param limit: The maximum number of subscriptions to retrieve.
        :type limit: int
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(ResourceListOfSubscription, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'filter',
            'sort_by',
            'page',
            'limit'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_subscriptions" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('filter') is not None:  # noqa: E501
            _query_params.append(('filter', _params['filter']))

        if _params.get('sort_by') is not None:  # noqa: E501
            _query_params.append(('sortBy', _params['sort_by']))

        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        if _params.get('limit') is not None:  # noqa: E501
            _query_params.append(('limit', _params['limit']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "ResourceListOfSubscription",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/notifications/api/subscriptions', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def update_subscription(self, scope: StrictStr, code: StrictStr, update_subscription: UpdateSubscription, **kwargs) -> Subscription:
        """UpdateSubscription: Update an existing subscription.  # noqa: E501

        :param scope: The scope that identifies a subscription (required)
        :type scope: str
        :param code: The code that identifies a subscription (required)
        :type code: str
        :param update_subscription: The data to update a subscription (required)
        :type update_subscription: UpdateSubscription
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: Subscription
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the update_subscription_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.update_subscription_with_http_info(scope, code, update_subscription, **kwargs)  # noqa: E501

    @validate_call
    def update_subscription_with_http_info(self, scope: StrictStr, code: StrictStr, update_subscription: UpdateSubscription, **kwargs) -> ApiResponse[Subscription]:
        """UpdateSubscription: Update an existing subscription.  # noqa: E501

        :param scope: The scope that identifies a subscription (required)
        :type scope: str
        :param code: The code that identifies a subscription (required)
        :type code: str
        :param update_subscription: The data to update a subscription (required)
        :type update_subscription: UpdateSubscription
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(Subscription, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'update_subscription'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_subscription" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['update_subscription'] is not None:
            _body_params = _params['update_subscription']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.sync_api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "Subscription",
            '400': "LusidValidationProblemDetails",
            '404': "str",
        }

        return self.sync_api_client.call_api(
            '/notifications/api/subscriptions/{scope}/{code}', 'PUT',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)


  # --- ASYNC API METHODS ---


    @validate_call
    async def create_subscription_async(self, create_subscription: CreateSubscription, **kwargs) -> Subscription:
            """CreateSubscription: Create a new subscription.  # noqa: E501
            
            :param create_subscription: The data to create a subscription (required)
            :type create_subscription: CreateSubscription
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: Subscription
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the create_subscription_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.create_subscription_with_http_info_async(create_subscription, **kwargs)  # noqa: E501

    @validate_call
    async def create_subscription_with_http_info_async(self, create_subscription: CreateSubscription, **kwargs) -> ApiResponse[Subscription]:
            """CreateSubscription: Create a new subscription.  # noqa: E501


            :param create_subscription: The data to create a subscription (required)
            :type create_subscription: CreateSubscription
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(Subscription, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'create_subscription'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method create_subscription" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}

            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            if _params['create_subscription'] is not None:
                _body_params = _params['create_subscription']

            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['application/json'])  # noqa: E501

            # set the HTTP header `Content-Type`
            _content_types_list = _params.get('_content_type',
                self.api_client.select_header_content_type(
                    ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
            if _content_types_list:
                    _header_params['Content-Type'] = _content_types_list

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '201': "Subscription",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/notifications/api/subscriptions', 'POST',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def delete_subscription_async(self, scope: StrictStr, code: StrictStr, **kwargs) -> None:
            """DeleteSubscription: Delete a subscription.  # noqa: E501
            
            :param scope: The scope that identifies a subscription (required)
            :type scope: str
            :param code: The code that identifies a subscription (required)
            :type code: str
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: None
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the delete_subscription_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.delete_subscription_with_http_info_async(scope, code, **kwargs)  # noqa: E501

    @validate_call
    async def delete_subscription_with_http_info_async(self, scope: StrictStr, code: StrictStr, **kwargs) -> None:
            """DeleteSubscription: Delete a subscription.  # noqa: E501


            :param scope: The scope that identifies a subscription (required)
            :type scope: str
            :param code: The code that identifies a subscription (required)
            :type code: str
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: None
            """

            _params = locals()

            _all_params = [
                'scope',
                'code'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method delete_subscription" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']


            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['application/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {}

            return await self.api_client.call_api_async(
                '/notifications/api/subscriptions/{scope}/{code}', 'DELETE',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def get_subscription_async(self, scope: StrictStr, code: StrictStr, **kwargs) -> Subscription:
            """GetSubscription: Get a subscription.  # noqa: E501
            
            :param scope: The scope that identifies a subscription (required)
            :type scope: str
            :param code: The code that identifies a subscription (required)
            :type code: str
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: Subscription
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the get_subscription_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.get_subscription_with_http_info_async(scope, code, **kwargs)  # noqa: E501

    @validate_call
    async def get_subscription_with_http_info_async(self, scope: StrictStr, code: StrictStr, **kwargs) -> ApiResponse[Subscription]:
            """GetSubscription: Get a subscription.  # noqa: E501


            :param scope: The scope that identifies a subscription (required)
            :type scope: str
            :param code: The code that identifies a subscription (required)
            :type code: str
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(Subscription, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'code'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method get_subscription" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']


            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['application/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "Subscription",
                '400': "LusidValidationProblemDetails",
                '404': "str",
            }

            return await self.api_client.call_api_async(
                '/notifications/api/subscriptions/{scope}/{code}', 'GET',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def list_subscriptions_async(self, filter: Optional[StrictStr] = None, sort_by: Optional[StrictStr] = None, page: Optional[StrictStr] = None, limit: Optional[int] = None, **kwargs) -> ResourceListOfSubscription:
            """ListSubscriptions: List subscriptions.  # noqa: E501
            
            :param filter: Expression to filter the result set. Read more about <a href=\"https://support.lusid.com/filtering-results-from-lusid\"> filtering results from LUSID</a>.
            :type filter: str
            :param sort_by: Fields to order the result set. Read more about <a href=\"https://support.lusid.com/filtering-results-from-lusid\"> filtering results from LUSID</a>
            :type sort_by: str
            :param page: Encoded page string returned from a previous search result that will retrieve the next page of data. When this field is supplied the filter  field should not be supplied.
            :type page: str
            :param limit: The maximum number of subscriptions to retrieve.
            :type limit: int
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: ResourceListOfSubscription
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the list_subscriptions_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.list_subscriptions_with_http_info_async(filter, sort_by, page, limit, **kwargs)  # noqa: E501

    @validate_call
    async def list_subscriptions_with_http_info_async(self, filter: Optional[StrictStr] = None, sort_by: Optional[StrictStr] = None, page: Optional[StrictStr] = None, limit: Optional[int] = None, **kwargs) -> ApiResponse[ResourceListOfSubscription]:
            """ListSubscriptions: List subscriptions.  # noqa: E501


            :param filter: Expression to filter the result set. Read more about <a href=\"https://support.lusid.com/filtering-results-from-lusid\"> filtering results from LUSID</a>.
            :type filter: str
            :param sort_by: Fields to order the result set. Read more about <a href=\"https://support.lusid.com/filtering-results-from-lusid\"> filtering results from LUSID</a>
            :type sort_by: str
            :param page: Encoded page string returned from a previous search result that will retrieve the next page of data. When this field is supplied the filter  field should not be supplied.
            :type page: str
            :param limit: The maximum number of subscriptions to retrieve.
            :type limit: int
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(ResourceListOfSubscription, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'filter',
                'sort_by',
                'page',
                'limit'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method list_subscriptions" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}

            # process the query parameters
            _query_params = []
            if _params.get('filter') is not None:  # noqa: E501
                _query_params.append(('filter', _params['filter']))

            if _params.get('sort_by') is not None:  # noqa: E501
                _query_params.append(('sortBy', _params['sort_by']))

            if _params.get('page') is not None:  # noqa: E501
                _query_params.append(('page', _params['page']))

            if _params.get('limit') is not None:  # noqa: E501
                _query_params.append(('limit', _params['limit']))

            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['application/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "ResourceListOfSubscription",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/notifications/api/subscriptions', 'GET',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def update_subscription_async(self, scope: StrictStr, code: StrictStr, update_subscription: UpdateSubscription, **kwargs) -> Subscription:
            """UpdateSubscription: Update an existing subscription.  # noqa: E501
            
            :param scope: The scope that identifies a subscription (required)
            :type scope: str
            :param code: The code that identifies a subscription (required)
            :type code: str
            :param update_subscription: The data to update a subscription (required)
            :type update_subscription: UpdateSubscription
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: Subscription
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the update_subscription_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.update_subscription_with_http_info_async(scope, code, update_subscription, **kwargs)  # noqa: E501

    @validate_call
    async def update_subscription_with_http_info_async(self, scope: StrictStr, code: StrictStr, update_subscription: UpdateSubscription, **kwargs) -> ApiResponse[Subscription]:
            """UpdateSubscription: Update an existing subscription.  # noqa: E501


            :param scope: The scope that identifies a subscription (required)
            :type scope: str
            :param code: The code that identifies a subscription (required)
            :type code: str
            :param update_subscription: The data to update a subscription (required)
            :type update_subscription: UpdateSubscription
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(Subscription, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'code',
                'update_subscription'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method update_subscription" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']


            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            if _params['update_subscription'] is not None:
                _body_params = _params['update_subscription']

            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['application/json'])  # noqa: E501

            # set the HTTP header `Content-Type`
            _content_types_list = _params.get('_content_type',
                self.api_client.select_header_content_type(
                    ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
            if _content_types_list:
                    _header_params['Content-Type'] = _content_types_list

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "Subscription",
                '400': "LusidValidationProblemDetails",
                '404': "str",
            }

            return await self.api_client.call_api_async(
                '/notifications/api/subscriptions/{scope}/{code}', 'PUT',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)



