# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

from __future__ import annotations
import pprint
import re  # noqa: F401
import json
from typing import Optional, List, Dict, Union, Annotated, Tuple, Any, TYPE_CHECKING
from datetime import datetime



from pydantic import StrictStr, Field, BaseModel, StrictInt, StrictBool, StrictFloat, StrictBytes, ConfigDict, field_validator, conlist 


class SearchBody(BaseModel):
    """
    DTO representing the search query  # noqa: E501
    """
    with_path:  Optional[StrictStr] = Field(default=None,alias="withPath", description="Optional path field to limit the search to result with a matching (case insensitive) path") 
    name:  StrictStr = Field(...,alias="name", description="Name of the file or folder to be searched") 
    __properties = ["withPath", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __str__(self):
        """For `print` and `pprint`"""
        return pprint.pformat(self. model_dump(by_alias=False))

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self. model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SearchBody:
        """Create an instance of SearchBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self. model_dump(by_alias=True,
                          mode='json',
                          exclude={
                          },
                          exclude_none=True)
        # set to None if with_path (nullable) is None
        # and model_fields_set contains the field
        if self.with_path is None and "with_path" in self.model_fields_set:
            _dict['withPath'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SearchBody:
        """Create an instance of SearchBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SearchBody.model_validate(obj)

        _obj = SearchBody.model_validate({
            "with_path": obj.get("withPath"),
            "name": obj.get("name")
        })
        return _obj

SearchBody.model_rebuild()

