# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import re  # noqa: F401
import io
import warnings

from pydantic import validate_call, ValidationError, Field, StrictStr
from typing import overload, Optional, Union, Awaitable
from typing_extensions import Annotated

import finbourne.sdk.services.lusid.models as packageModels
from pydantic import Field, field_validator
from typing_extensions import Annotated
from finbourne.sdk.services.lusid.models.complete_relationship import CompleteRelationship
from finbourne.sdk.services.lusid.models.create_relationship_request import CreateRelationshipRequest
from finbourne.sdk.services.lusid.models.delete_relationship_request import DeleteRelationshipRequest
from finbourne.sdk.services.lusid.models.deleted_entity_response import DeletedEntityResponse
from finbourne.sdk.api_client import ApiClient
from finbourne.sdk.api_response import ApiResponse
from finbourne.sdk.extensions.api_client import SyncApiClient
from finbourne.sdk.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)
from finbourne.sdk.extensions.configuration_options import ConfigurationOptions

class RelationshipsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client = None, sync_api_client = None) -> None:
        if sync_api_client is not None:
            self.sync_api_client = sync_api_client
        elif api_client is not None:
            self.api_client = api_client
        else:
            self.api_client = ApiClient.get_default()

    @validate_call
    def create_relationship(self, scope: StrictStr, code: StrictStr, create_relationship_request: CreateRelationshipRequest, **kwargs) -> CompleteRelationship:
        """CreateRelationship: Create Relationship  # noqa: E501

        Create a relationship between two entity objects by their identifiers  # noqa: E501
        :param scope: The scope of the relationship (required)
        :type scope: str
        :param code: The code of the relationship (required)
        :type code: str
        :param create_relationship_request: The details of the relationship to create. (required)
        :type create_relationship_request: CreateRelationshipRequest
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: CompleteRelationship
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the create_relationship_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.create_relationship_with_http_info(scope, code, create_relationship_request, **kwargs)  # noqa: E501

    @validate_call
    def create_relationship_with_http_info(self, scope: StrictStr, code: StrictStr, create_relationship_request: CreateRelationshipRequest, **kwargs) -> ApiResponse[CompleteRelationship]:
        """CreateRelationship: Create Relationship  # noqa: E501

        Create a relationship between two entity objects by their identifiers  # noqa: E501
        :param scope: The scope of the relationship (required)
        :type scope: str
        :param code: The code of the relationship (required)
        :type code: str
        :param create_relationship_request: The details of the relationship to create. (required)
        :type create_relationship_request: CreateRelationshipRequest
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(CompleteRelationship, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'create_relationship_request'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_relationship" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['create_relationship_request'] is not None:
            _body_params = _params['create_relationship_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.sync_api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '201': "CompleteRelationship",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/api/api/relationshipdefinitions/{scope}/{code}/relationships', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def delete_relationship(self, scope: StrictStr, code: StrictStr, delete_relationship_request: DeleteRelationshipRequest, **kwargs) -> DeletedEntityResponse:
        """[EARLY ACCESS] DeleteRelationship: Delete Relationship  # noqa: E501

        Delete a relationship between two entity objects represented by their identifiers  # noqa: E501
        :param scope: The scope of the relationship (required)
        :type scope: str
        :param code: The code of the relationship (required)
        :type code: str
        :param delete_relationship_request: The details of the relationship to delete. (required)
        :type delete_relationship_request: DeleteRelationshipRequest
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: DeletedEntityResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the delete_relationship_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.delete_relationship_with_http_info(scope, code, delete_relationship_request, **kwargs)  # noqa: E501

    @validate_call
    def delete_relationship_with_http_info(self, scope: StrictStr, code: StrictStr, delete_relationship_request: DeleteRelationshipRequest, **kwargs) -> ApiResponse[DeletedEntityResponse]:
        """[EARLY ACCESS] DeleteRelationship: Delete Relationship  # noqa: E501

        Delete a relationship between two entity objects represented by their identifiers  # noqa: E501
        :param scope: The scope of the relationship (required)
        :type scope: str
        :param code: The code of the relationship (required)
        :type code: str
        :param delete_relationship_request: The details of the relationship to delete. (required)
        :type delete_relationship_request: DeleteRelationshipRequest
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(DeletedEntityResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'delete_relationship_request'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_relationship" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['delete_relationship_request'] is not None:
            _body_params = _params['delete_relationship_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.sync_api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "DeletedEntityResponse",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/api/api/relationshipdefinitions/{scope}/{code}/relationships/$delete', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)


  # --- ASYNC API METHODS ---


    @validate_call
    async def create_relationship_async(self, scope: StrictStr, code: StrictStr, create_relationship_request: CreateRelationshipRequest, **kwargs) -> CompleteRelationship:
            """CreateRelationship: Create Relationship  # noqa: E501
            Create a relationship between two entity objects by their identifiers  # noqa: E501
            
            :param scope: The scope of the relationship (required)
            :type scope: str
            :param code: The code of the relationship (required)
            :type code: str
            :param create_relationship_request: The details of the relationship to create. (required)
            :type create_relationship_request: CreateRelationshipRequest
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: CompleteRelationship
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the create_relationship_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.create_relationship_with_http_info_async(scope, code, create_relationship_request, **kwargs)  # noqa: E501

    @validate_call
    async def create_relationship_with_http_info_async(self, scope: StrictStr, code: StrictStr, create_relationship_request: CreateRelationshipRequest, **kwargs) -> ApiResponse[CompleteRelationship]:
            """CreateRelationship: Create Relationship  # noqa: E501

            Create a relationship between two entity objects by their identifiers  # noqa: E501

            :param scope: The scope of the relationship (required)
            :type scope: str
            :param code: The code of the relationship (required)
            :type code: str
            :param create_relationship_request: The details of the relationship to create. (required)
            :type create_relationship_request: CreateRelationshipRequest
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(CompleteRelationship, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'code',
                'create_relationship_request'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method create_relationship" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']


            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            if _params['create_relationship_request'] is not None:
                _body_params = _params['create_relationship_request']

            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # set the HTTP header `Content-Type`
            _content_types_list = _params.get('_content_type',
                self.api_client.select_header_content_type(
                    ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
            if _content_types_list:
                    _header_params['Content-Type'] = _content_types_list

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '201': "CompleteRelationship",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/api/api/relationshipdefinitions/{scope}/{code}/relationships', 'POST',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def delete_relationship_async(self, scope: StrictStr, code: StrictStr, delete_relationship_request: DeleteRelationshipRequest, **kwargs) -> DeletedEntityResponse:
            """[EARLY ACCESS] DeleteRelationship: Delete Relationship  # noqa: E501
            Delete a relationship between two entity objects represented by their identifiers  # noqa: E501
            
            :param scope: The scope of the relationship (required)
            :type scope: str
            :param code: The code of the relationship (required)
            :type code: str
            :param delete_relationship_request: The details of the relationship to delete. (required)
            :type delete_relationship_request: DeleteRelationshipRequest
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: DeletedEntityResponse
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the delete_relationship_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.delete_relationship_with_http_info_async(scope, code, delete_relationship_request, **kwargs)  # noqa: E501

    @validate_call
    async def delete_relationship_with_http_info_async(self, scope: StrictStr, code: StrictStr, delete_relationship_request: DeleteRelationshipRequest, **kwargs) -> ApiResponse[DeletedEntityResponse]:
            """[EARLY ACCESS] DeleteRelationship: Delete Relationship  # noqa: E501

            Delete a relationship between two entity objects represented by their identifiers  # noqa: E501

            :param scope: The scope of the relationship (required)
            :type scope: str
            :param code: The code of the relationship (required)
            :type code: str
            :param delete_relationship_request: The details of the relationship to delete. (required)
            :type delete_relationship_request: DeleteRelationshipRequest
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(DeletedEntityResponse, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'code',
                'delete_relationship_request'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method delete_relationship" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']


            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            if _params['delete_relationship_request'] is not None:
                _body_params = _params['delete_relationship_request']

            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # set the HTTP header `Content-Type`
            _content_types_list = _params.get('_content_type',
                self.api_client.select_header_content_type(
                    ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
            if _content_types_list:
                    _header_params['Content-Type'] = _content_types_list

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "DeletedEntityResponse",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/api/api/relationshipdefinitions/{scope}/{code}/relationships/$delete', 'POST',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)



