# coding: utf-8

"""
    Merged OpenAPI Specification

    Merged OpenAPI spec from multiple files  # noqa: E501

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""

import re  # noqa: F401
import io
import warnings

from pydantic import validate_call, ValidationError, Field, StrictStr
from typing import overload, Optional, Union, Awaitable
from typing_extensions import Annotated

import finbourne.sdk.services.lusid.models as packageModels
from datetime import datetime
from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from finbourne.sdk.services.lusid.models.deleted_entity_response import DeletedEntityResponse
from finbourne.sdk.services.lusid.models.paged_resource_list_of_resource_record import PagedResourceListOfResourceRecord
from finbourne.sdk.services.lusid.models.resource_list_of_scope_definition import ResourceListOfScopeDefinition
from finbourne.sdk.services.lusid.models.resource_list_of_string import ResourceListOfString
from finbourne.sdk.services.lusid.models.resource_record import ResourceRecord
from finbourne.sdk.services.lusid.models.upsert_resource_record_request import UpsertResourceRecordRequest
from finbourne.sdk.api_client import ApiClient
from finbourne.sdk.api_response import ApiResponse
from finbourne.sdk.extensions.api_client import SyncApiClient
from finbourne.sdk.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)
from finbourne.sdk.extensions.configuration_options import ConfigurationOptions

class ResourceRecordApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client = None, sync_api_client = None) -> None:
        if sync_api_client is not None:
            self.sync_api_client = sync_api_client
        elif api_client is not None:
            self.api_client = api_client
        else:
            self.api_client = ApiClient.get_default()

    @validate_call
    def delete_resource_record(self, scope: StrictStr, code: StrictStr, resource_id: StrictStr, **kwargs) -> DeletedEntityResponse:
        """[EARLY ACCESS] DeleteResourceRecord: Delete a Resource Record  # noqa: E501

        Delete a resource record.  # noqa: E501
        :param scope: The scope of the resource record. (required)
        :type scope: str
        :param code: The code of the resource record. (required)
        :type code: str
        :param resource_id: The resource identifier of the resource record. (required)
        :type resource_id: str
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: DeletedEntityResponse
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the delete_resource_record_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.delete_resource_record_with_http_info(scope, code, resource_id, **kwargs)  # noqa: E501

    @validate_call
    def delete_resource_record_with_http_info(self, scope: StrictStr, code: StrictStr, resource_id: StrictStr, **kwargs) -> ApiResponse[DeletedEntityResponse]:
        """[EARLY ACCESS] DeleteResourceRecord: Delete a Resource Record  # noqa: E501

        Delete a resource record.  # noqa: E501
        :param scope: The scope of the resource record. (required)
        :type scope: str
        :param code: The code of the resource record. (required)
        :type code: str
        :param resource_id: The resource identifier of the resource record. (required)
        :type resource_id: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(DeletedEntityResponse, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'resource_id'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_resource_record" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']

        if _params['resource_id']:
            _path_params['resourceId'] = _params['resource_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "DeletedEntityResponse",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/api/api/resourcerecords/{scope}/{code}/{resourceId}', 'DELETE',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def get_resource_record(self, scope: StrictStr, code: StrictStr, resource_id: StrictStr, as_at: Optional[datetime] = None, **kwargs) -> ResourceRecord:
        """[EARLY ACCESS] GetResourceRecord: Get a Resource Record  # noqa: E501

        Retrieve a resource record by its identifier.  # noqa: E501
        :param scope: The scope of the resource record. (required)
        :type scope: str
        :param code: The code of the resource record. (required)
        :type code: str
        :param resource_id: The resource identifier of the resource record. (required)
        :type resource_id: str
        :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
        :type as_at: datetime
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: ResourceRecord
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_resource_record_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.get_resource_record_with_http_info(scope, code, resource_id, as_at, **kwargs)  # noqa: E501

    @validate_call
    def get_resource_record_with_http_info(self, scope: StrictStr, code: StrictStr, resource_id: StrictStr, as_at: Optional[datetime] = None, **kwargs) -> ApiResponse[ResourceRecord]:
        """[EARLY ACCESS] GetResourceRecord: Get a Resource Record  # noqa: E501

        Retrieve a resource record by its identifier.  # noqa: E501
        :param scope: The scope of the resource record. (required)
        :type scope: str
        :param code: The code of the resource record. (required)
        :type code: str
        :param resource_id: The resource identifier of the resource record. (required)
        :type resource_id: str
        :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
        :type as_at: datetime
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(ResourceRecord, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'resource_id',
            'as_at'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_resource_record" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']

        if _params['resource_id']:
            _path_params['resourceId'] = _params['resource_id']


        # process the query parameters
        _query_params = []
        if _params.get('as_at') is not None:  # noqa: E501
            if isinstance(_params['as_at'], datetime):
                _query_params.append(('asAt', _params['as_at'].strftime(self.sync_api_client.configuration.datetime_format)))
            else:
                _query_params.append(('asAt', _params['as_at']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "ResourceRecord",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/api/api/resourcerecords/{scope}/{code}/{resourceId}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def list_resource_record_codes(self, scope: StrictStr, as_at: Optional[datetime] = None, sort_order: Optional[StrictStr] = None, **kwargs) -> ResourceListOfString:
        """[EARLY ACCESS] ListResourceRecordCodes: List Resource Records Codes for Scope  # noqa: E501

        List all resource records matching particular criteria.  # noqa: E501
        :param scope: The scope of the resource record. (required)
        :type scope: str
        :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
        :type as_at: datetime
        :param sort_order: Order of the sort - either \"ASC\" or \"DESC\"
        :type sort_order: str
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: ResourceListOfString
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_resource_record_codes_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.list_resource_record_codes_with_http_info(scope, as_at, sort_order, **kwargs)  # noqa: E501

    @validate_call
    def list_resource_record_codes_with_http_info(self, scope: StrictStr, as_at: Optional[datetime] = None, sort_order: Optional[StrictStr] = None, **kwargs) -> ApiResponse[ResourceListOfString]:
        """[EARLY ACCESS] ListResourceRecordCodes: List Resource Records Codes for Scope  # noqa: E501

        List all resource records matching particular criteria.  # noqa: E501
        :param scope: The scope of the resource record. (required)
        :type scope: str
        :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
        :type as_at: datetime
        :param sort_order: Order of the sort - either \"ASC\" or \"DESC\"
        :type sort_order: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(ResourceListOfString, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'as_at',
            'sort_order'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_resource_record_codes" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']


        # process the query parameters
        _query_params = []
        if _params.get('as_at') is not None:  # noqa: E501
            if isinstance(_params['as_at'], datetime):
                _query_params.append(('asAt', _params['as_at'].strftime(self.sync_api_client.configuration.datetime_format)))
            else:
                _query_params.append(('asAt', _params['as_at']))

        if _params.get('sort_order') is not None:  # noqa: E501
            _query_params.append(('sortOrder', _params['sort_order']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "ResourceListOfString",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/api/api/resourcerecords/{scope}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def list_resource_record_scopes(self, as_at: Optional[datetime] = None, page: Optional[StrictStr] = None, limit: Optional[int] = None, **kwargs) -> ResourceListOfScopeDefinition:
        """[EARLY ACCESS] ListResourceRecordScopes: List Resource Record Scopes  # noqa: E501

        List all resource records matching particular criteria.  # noqa: E501
        :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
        :type as_at: datetime
        :param page: The pagination token to use to continue listing resource records from a previous call.
        :type page: str
        :param limit: When paginating, limit the number of returned results to this many.
        :type limit: int
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: ResourceListOfScopeDefinition
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_resource_record_scopes_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.list_resource_record_scopes_with_http_info(as_at, page, limit, **kwargs)  # noqa: E501

    @validate_call
    def list_resource_record_scopes_with_http_info(self, as_at: Optional[datetime] = None, page: Optional[StrictStr] = None, limit: Optional[int] = None, **kwargs) -> ApiResponse[ResourceListOfScopeDefinition]:
        """[EARLY ACCESS] ListResourceRecordScopes: List Resource Record Scopes  # noqa: E501

        List all resource records matching particular criteria.  # noqa: E501
        :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
        :type as_at: datetime
        :param page: The pagination token to use to continue listing resource records from a previous call.
        :type page: str
        :param limit: When paginating, limit the number of returned results to this many.
        :type limit: int
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(ResourceListOfScopeDefinition, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'as_at',
            'page',
            'limit'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_resource_record_scopes" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('as_at') is not None:  # noqa: E501
            if isinstance(_params['as_at'], datetime):
                _query_params.append(('asAt', _params['as_at'].strftime(self.sync_api_client.configuration.datetime_format)))
            else:
                _query_params.append(('asAt', _params['as_at']))

        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        if _params.get('limit') is not None:  # noqa: E501
            _query_params.append(('limit', _params['limit']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "ResourceListOfScopeDefinition",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/api/api/resourcerecords', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def list_resource_records(self, scope: StrictStr, code: StrictStr, as_at: Optional[datetime] = None, page: Optional[StrictStr] = None, sort_by: Optional[List[str]] = None, limit: Optional[int] = None, filter: Optional[StrictStr] = None, **kwargs) -> PagedResourceListOfResourceRecord:
        """[EARLY ACCESS] ListResourceRecords: List Resource Records  # noqa: E501

        List all resource records matching particular criteria.  # noqa: E501
        :param scope: The scope of the resource record. (required)
        :type scope: str
        :param code: The code of the resource record. (required)
        :type code: str
        :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
        :type as_at: datetime
        :param page: The pagination token to use to continue listing resource records from a previous call.
        :type page: str
        :param sort_by: A list of field names to sort by, each suffixed by \" ASC\" or \" DESC\"
        :type sort_by: List[str]
        :param limit: When paginating, limit the number of returned results to this many.
        :type limit: int
        :param filter: Expression to filter the result set.
        :type filter: str
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: PagedResourceListOfResourceRecord
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the list_resource_records_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.list_resource_records_with_http_info(scope, code, as_at, page, sort_by, limit, filter, **kwargs)  # noqa: E501

    @validate_call
    def list_resource_records_with_http_info(self, scope: StrictStr, code: StrictStr, as_at: Optional[datetime] = None, page: Optional[StrictStr] = None, sort_by: Optional[List[str]] = None, limit: Optional[int] = None, filter: Optional[StrictStr] = None, **kwargs) -> ApiResponse[PagedResourceListOfResourceRecord]:
        """[EARLY ACCESS] ListResourceRecords: List Resource Records  # noqa: E501

        List all resource records matching particular criteria.  # noqa: E501
        :param scope: The scope of the resource record. (required)
        :type scope: str
        :param code: The code of the resource record. (required)
        :type code: str
        :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
        :type as_at: datetime
        :param page: The pagination token to use to continue listing resource records from a previous call.
        :type page: str
        :param sort_by: A list of field names to sort by, each suffixed by \" ASC\" or \" DESC\"
        :type sort_by: List[str]
        :param limit: When paginating, limit the number of returned results to this many.
        :type limit: int
        :param filter: Expression to filter the result set.
        :type filter: str
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(PagedResourceListOfResourceRecord, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'scope',
            'code',
            'as_at',
            'page',
            'sort_by',
            'limit',
            'filter'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method list_resource_records" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['scope']:
            _path_params['scope'] = _params['scope']

        if _params['code']:
            _path_params['code'] = _params['code']


        # process the query parameters
        _query_params = []
        if _params.get('as_at') is not None:  # noqa: E501
            if isinstance(_params['as_at'], datetime):
                _query_params.append(('asAt', _params['as_at'].strftime(self.sync_api_client.configuration.datetime_format)))
            else:
                _query_params.append(('asAt', _params['as_at']))

        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        if _params.get('sort_by') is not None:  # noqa: E501
            _query_params.append(('sortBy', _params['sort_by']))
            _collection_formats['sortBy'] = 'multi'

        if _params.get('limit') is not None:  # noqa: E501
            _query_params.append(('limit', _params['limit']))

        if _params.get('filter') is not None:  # noqa: E501
            _query_params.append(('filter', _params['filter']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '200': "PagedResourceListOfResourceRecord",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/api/api/resourcerecords/{scope}/{code}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    def upsert_resource_record(self, upsert_resource_record_request: UpsertResourceRecordRequest, **kwargs) -> ResourceRecord:
        """[EARLY ACCESS] UpsertResourceRecord: Upsert a Resource Record  # noqa: E501

        Create or update a resource record.  # noqa: E501
        :param upsert_resource_record_request: The resource record to upsert. (required)
        :type upsert_resource_record_request: UpsertResourceRecordRequest
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :return: Returns the result object.
        :rtype: ResourceRecord
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the upsert_resource_record_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)

        return self.upsert_resource_record_with_http_info(upsert_resource_record_request, **kwargs)  # noqa: E501

    @validate_call
    def upsert_resource_record_with_http_info(self, upsert_resource_record_request: UpsertResourceRecordRequest, **kwargs) -> ApiResponse[ResourceRecord]:
        """[EARLY ACCESS] UpsertResourceRecord: Upsert a Resource Record  # noqa: E501

        Create or update a resource record.  # noqa: E501
        :param upsert_resource_record_request: The resource record to upsert. (required)
        :type upsert_resource_record_request: UpsertResourceRecordRequest
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
        :param opts: Configuration options for this request
        :type opts: ConfigurationOptions, optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
        :rtype: tuple(ResourceRecord, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'upsert_resource_record_request'
        ]
        _all_params.extend(
            [
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
                'opts'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method upsert_resource_record" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['upsert_resource_record_request'] is not None:
            _body_params = _params['upsert_resource_record_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.sync_api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.sync_api_client.select_header_content_type(
                ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['oauth2']  # noqa: E501

        _response_types_map = {
            '201': "ResourceRecord",
            '400': "LusidValidationProblemDetails",
        }

        return self.sync_api_client.call_api(
            '/api/api/resourcerecords', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            opts=_params.get('opts'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'), model_klass=packageModels)


  # --- ASYNC API METHODS ---


    @validate_call
    async def delete_resource_record_async(self, scope: StrictStr, code: StrictStr, resource_id: StrictStr, **kwargs) -> DeletedEntityResponse:
            """[EARLY ACCESS] DeleteResourceRecord: Delete a Resource Record  # noqa: E501
            Delete a resource record.  # noqa: E501
            
            :param scope: The scope of the resource record. (required)
            :type scope: str
            :param code: The code of the resource record. (required)
            :type code: str
            :param resource_id: The resource identifier of the resource record. (required)
            :type resource_id: str
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: DeletedEntityResponse
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the delete_resource_record_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.delete_resource_record_with_http_info_async(scope, code, resource_id, **kwargs)  # noqa: E501

    @validate_call
    async def delete_resource_record_with_http_info_async(self, scope: StrictStr, code: StrictStr, resource_id: StrictStr, **kwargs) -> ApiResponse[DeletedEntityResponse]:
            """[EARLY ACCESS] DeleteResourceRecord: Delete a Resource Record  # noqa: E501

            Delete a resource record.  # noqa: E501

            :param scope: The scope of the resource record. (required)
            :type scope: str
            :param code: The code of the resource record. (required)
            :type code: str
            :param resource_id: The resource identifier of the resource record. (required)
            :type resource_id: str
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(DeletedEntityResponse, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'code',
                'resource_id'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method delete_resource_record" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']

            if _params['resource_id']:
                _path_params['resourceId'] = _params['resource_id']


            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "DeletedEntityResponse",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/api/api/resourcerecords/{scope}/{code}/{resourceId}', 'DELETE',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def get_resource_record_async(self, scope: StrictStr, code: StrictStr, resource_id: StrictStr, as_at: Optional[datetime] = None, **kwargs) -> ResourceRecord:
            """[EARLY ACCESS] GetResourceRecord: Get a Resource Record  # noqa: E501
            Retrieve a resource record by its identifier.  # noqa: E501
            
            :param scope: The scope of the resource record. (required)
            :type scope: str
            :param code: The code of the resource record. (required)
            :type code: str
            :param resource_id: The resource identifier of the resource record. (required)
            :type resource_id: str
            :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
            :type as_at: datetime
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: ResourceRecord
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the get_resource_record_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.get_resource_record_with_http_info_async(scope, code, resource_id, as_at, **kwargs)  # noqa: E501

    @validate_call
    async def get_resource_record_with_http_info_async(self, scope: StrictStr, code: StrictStr, resource_id: StrictStr, as_at: Optional[datetime] = None, **kwargs) -> ApiResponse[ResourceRecord]:
            """[EARLY ACCESS] GetResourceRecord: Get a Resource Record  # noqa: E501

            Retrieve a resource record by its identifier.  # noqa: E501

            :param scope: The scope of the resource record. (required)
            :type scope: str
            :param code: The code of the resource record. (required)
            :type code: str
            :param resource_id: The resource identifier of the resource record. (required)
            :type resource_id: str
            :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
            :type as_at: datetime
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(ResourceRecord, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'code',
                'resource_id',
                'as_at'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method get_resource_record" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']

            if _params['resource_id']:
                _path_params['resourceId'] = _params['resource_id']


            # process the query parameters
            _query_params = []
            if _params.get('as_at') is not None:  # noqa: E501
                if isinstance(_params['as_at'], datetime):
                    _query_params.append(('asAt', _params['as_at'].strftime(self.api_client.configuration.datetime_format)))
                else:
                    _query_params.append(('asAt', _params['as_at']))

            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "ResourceRecord",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/api/api/resourcerecords/{scope}/{code}/{resourceId}', 'GET',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def list_resource_record_codes_async(self, scope: StrictStr, as_at: Optional[datetime] = None, sort_order: Optional[StrictStr] = None, **kwargs) -> ResourceListOfString:
            """[EARLY ACCESS] ListResourceRecordCodes: List Resource Records Codes for Scope  # noqa: E501
            List all resource records matching particular criteria.  # noqa: E501
            
            :param scope: The scope of the resource record. (required)
            :type scope: str
            :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
            :type as_at: datetime
            :param sort_order: Order of the sort - either \"ASC\" or \"DESC\"
            :type sort_order: str
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: ResourceListOfString
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the list_resource_record_codes_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.list_resource_record_codes_with_http_info_async(scope, as_at, sort_order, **kwargs)  # noqa: E501

    @validate_call
    async def list_resource_record_codes_with_http_info_async(self, scope: StrictStr, as_at: Optional[datetime] = None, sort_order: Optional[StrictStr] = None, **kwargs) -> ApiResponse[ResourceListOfString]:
            """[EARLY ACCESS] ListResourceRecordCodes: List Resource Records Codes for Scope  # noqa: E501

            List all resource records matching particular criteria.  # noqa: E501

            :param scope: The scope of the resource record. (required)
            :type scope: str
            :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
            :type as_at: datetime
            :param sort_order: Order of the sort - either \"ASC\" or \"DESC\"
            :type sort_order: str
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(ResourceListOfString, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'as_at',
                'sort_order'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method list_resource_record_codes" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']


            # process the query parameters
            _query_params = []
            if _params.get('as_at') is not None:  # noqa: E501
                if isinstance(_params['as_at'], datetime):
                    _query_params.append(('asAt', _params['as_at'].strftime(self.api_client.configuration.datetime_format)))
                else:
                    _query_params.append(('asAt', _params['as_at']))

            if _params.get('sort_order') is not None:  # noqa: E501
                _query_params.append(('sortOrder', _params['sort_order']))

            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "ResourceListOfString",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/api/api/resourcerecords/{scope}', 'GET',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def list_resource_record_scopes_async(self, as_at: Optional[datetime] = None, page: Optional[StrictStr] = None, limit: Optional[int] = None, **kwargs) -> ResourceListOfScopeDefinition:
            """[EARLY ACCESS] ListResourceRecordScopes: List Resource Record Scopes  # noqa: E501
            List all resource records matching particular criteria.  # noqa: E501
            
            :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
            :type as_at: datetime
            :param page: The pagination token to use to continue listing resource records from a previous call.
            :type page: str
            :param limit: When paginating, limit the number of returned results to this many.
            :type limit: int
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: ResourceListOfScopeDefinition
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the list_resource_record_scopes_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.list_resource_record_scopes_with_http_info_async(as_at, page, limit, **kwargs)  # noqa: E501

    @validate_call
    async def list_resource_record_scopes_with_http_info_async(self, as_at: Optional[datetime] = None, page: Optional[StrictStr] = None, limit: Optional[int] = None, **kwargs) -> ApiResponse[ResourceListOfScopeDefinition]:
            """[EARLY ACCESS] ListResourceRecordScopes: List Resource Record Scopes  # noqa: E501

            List all resource records matching particular criteria.  # noqa: E501

            :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
            :type as_at: datetime
            :param page: The pagination token to use to continue listing resource records from a previous call.
            :type page: str
            :param limit: When paginating, limit the number of returned results to this many.
            :type limit: int
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(ResourceListOfScopeDefinition, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'as_at',
                'page',
                'limit'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method list_resource_record_scopes" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}

            # process the query parameters
            _query_params = []
            if _params.get('as_at') is not None:  # noqa: E501
                if isinstance(_params['as_at'], datetime):
                    _query_params.append(('asAt', _params['as_at'].strftime(self.api_client.configuration.datetime_format)))
                else:
                    _query_params.append(('asAt', _params['as_at']))

            if _params.get('page') is not None:  # noqa: E501
                _query_params.append(('page', _params['page']))

            if _params.get('limit') is not None:  # noqa: E501
                _query_params.append(('limit', _params['limit']))

            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "ResourceListOfScopeDefinition",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/api/api/resourcerecords', 'GET',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def list_resource_records_async(self, scope: StrictStr, code: StrictStr, as_at: Optional[datetime] = None, page: Optional[StrictStr] = None, sort_by: Optional[List[str]] = None, limit: Optional[int] = None, filter: Optional[StrictStr] = None, **kwargs) -> PagedResourceListOfResourceRecord:
            """[EARLY ACCESS] ListResourceRecords: List Resource Records  # noqa: E501
            List all resource records matching particular criteria.  # noqa: E501
            
            :param scope: The scope of the resource record. (required)
            :type scope: str
            :param code: The code of the resource record. (required)
            :type code: str
            :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
            :type as_at: datetime
            :param page: The pagination token to use to continue listing resource records from a previous call.
            :type page: str
            :param sort_by: A list of field names to sort by, each suffixed by \" ASC\" or \" DESC\"
            :type sort_by: List[str]
            :param limit: When paginating, limit the number of returned results to this many.
            :type limit: int
            :param filter: Expression to filter the result set.
            :type filter: str
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: PagedResourceListOfResourceRecord
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the list_resource_records_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.list_resource_records_with_http_info_async(scope, code, as_at, page, sort_by, limit, filter, **kwargs)  # noqa: E501

    @validate_call
    async def list_resource_records_with_http_info_async(self, scope: StrictStr, code: StrictStr, as_at: Optional[datetime] = None, page: Optional[StrictStr] = None, sort_by: Optional[List[str]] = None, limit: Optional[int] = None, filter: Optional[StrictStr] = None, **kwargs) -> ApiResponse[PagedResourceListOfResourceRecord]:
            """[EARLY ACCESS] ListResourceRecords: List Resource Records  # noqa: E501

            List all resource records matching particular criteria.  # noqa: E501

            :param scope: The scope of the resource record. (required)
            :type scope: str
            :param code: The code of the resource record. (required)
            :type code: str
            :param as_at: The asAt datetime at which to list the resource record. Defaults to return the latest version if not specified.
            :type as_at: datetime
            :param page: The pagination token to use to continue listing resource records from a previous call.
            :type page: str
            :param sort_by: A list of field names to sort by, each suffixed by \" ASC\" or \" DESC\"
            :type sort_by: List[str]
            :param limit: When paginating, limit the number of returned results to this many.
            :type limit: int
            :param filter: Expression to filter the result set.
            :type filter: str
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(PagedResourceListOfResourceRecord, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'scope',
                'code',
                'as_at',
                'page',
                'sort_by',
                'limit',
                'filter'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method list_resource_records" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}
            if _params['scope']:
                _path_params['scope'] = _params['scope']

            if _params['code']:
                _path_params['code'] = _params['code']


            # process the query parameters
            _query_params = []
            if _params.get('as_at') is not None:  # noqa: E501
                if isinstance(_params['as_at'], datetime):
                    _query_params.append(('asAt', _params['as_at'].strftime(self.api_client.configuration.datetime_format)))
                else:
                    _query_params.append(('asAt', _params['as_at']))

            if _params.get('page') is not None:  # noqa: E501
                _query_params.append(('page', _params['page']))

            if _params.get('sort_by') is not None:  # noqa: E501
                _query_params.append(('sortBy', _params['sort_by']))
                _collection_formats['sortBy'] = 'multi'

            if _params.get('limit') is not None:  # noqa: E501
                _query_params.append(('limit', _params['limit']))

            if _params.get('filter') is not None:  # noqa: E501
                _query_params.append(('filter', _params['filter']))

            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '200': "PagedResourceListOfResourceRecord",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/api/api/resourcerecords/{scope}/{code}', 'GET',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)

    @validate_call
    async def upsert_resource_record_async(self, upsert_resource_record_request: UpsertResourceRecordRequest, **kwargs) -> ResourceRecord:
            """[EARLY ACCESS] UpsertResourceRecord: Upsert a Resource Record  # noqa: E501
            Create or update a resource record.  # noqa: E501
            
            :param upsert_resource_record_request: The resource record to upsert. (required)
            :type upsert_resource_record_request: UpsertResourceRecordRequest
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :return: Returns an coroutine ApiResponse object.
            :rtype: ResourceRecord
            """
            kwargs['_return_http_data_only'] = True
            if '_preload_content' in kwargs:
                message = "Error! Please call the upsert_resource_record_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
                raise ValueError(message)

            return await self.upsert_resource_record_with_http_info_async(upsert_resource_record_request, **kwargs)  # noqa: E501

    @validate_call
    async def upsert_resource_record_with_http_info_async(self, upsert_resource_record_request: UpsertResourceRecordRequest, **kwargs) -> ApiResponse[ResourceRecord]:
            """[EARLY ACCESS] UpsertResourceRecord: Upsert a Resource Record  # noqa: E501

            Create or update a resource record.  # noqa: E501

            :param upsert_resource_record_request: The resource record to upsert. (required)
            :type upsert_resource_record_request: UpsertResourceRecordRequest
            :param _preload_content: if False, the ApiResponse.data will
                                    be set to none and raw_data will store the
                                    HTTP response body without reading/decoding.
                                    Default is True.
            :type _preload_content: bool, optional
            :param _return_http_data_only: response data instead of ApiResponse
                                          object with status code, headers, etc
            :type _return_http_data_only: bool, optional
            :param _request_timeout: Timeout setting. Do not use - use the opts parameter instead
            :param opts: Configuration options for this request
            :type opts: ConfigurationOptions, optional
            :param _request_auth: set to override the auth_settings for an a single
                                  request; this effectively ignores the authentication
                                  in the spec for a single request.
            :type _request_auth: dict, optional
            :type _content_type: string, optional: force content-type for the request
            :return: Returns an coroutine ApiResponse object.
            :rtype: tuple(ResourceRecord, status_code(int), headers(HTTPHeaderDict))
            """

            _params = locals()

            _all_params = [
                'upsert_resource_record_request'
            ]
            _all_params.extend(
                [
                    '_return_http_data_only',
                    '_preload_content',
                    '_request_timeout',
                    '_request_auth',
                    '_content_type',
                    '_headers',
                    'opts'
                ]
            )

            # validate the arguments
            for _key, _val in _params['kwargs'].items():
                if _key not in _all_params:
                    raise ApiTypeError(
                        "Got an unexpected keyword argument '%s'"
                        " to method upsert_resource_record" % _key
                    )
                _params[_key] = _val
            del _params['kwargs']

            _collection_formats = {}

            # process the path parameters
            _path_params = {}

            # process the query parameters
            _query_params = []
            # process the header parameters
            _header_params = dict(_params.get('_headers', {}))
            # process the form parameters
            _form_params = []
            _files = {}
            # process the body parameter
            _body_params = None
            if _params['upsert_resource_record_request'] is not None:
                _body_params = _params['upsert_resource_record_request']

            # set the HTTP header `Accept`
            _header_params['Accept'] = self.api_client.select_header_accept(
                ['text/plain', 'application/json', 'text/json'])  # noqa: E501

            # set the HTTP header `Content-Type`
            _content_types_list = _params.get('_content_type',
                self.api_client.select_header_content_type(
                    ['application/json-patch+json', 'application/json', 'text/json', 'application/*+json']))
            if _content_types_list:
                    _header_params['Content-Type'] = _content_types_list

            # authentication setting
            _auth_settings = ['oauth2']  # noqa: E501

            _response_types_map = {
                '201': "ResourceRecord",
                '400': "LusidValidationProblemDetails",
            }

            return await self.api_client.call_api_async(
                '/api/api/resourcerecords', 'POST',
                _path_params,
                _query_params,
                _header_params,
                body=_body_params,
                post_params=_form_params,
                files=_files,
                response_types_map=_response_types_map,
                auth_settings=_auth_settings,
                _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
                _preload_content=_params.get('_preload_content', True),
                _request_timeout=_params.get('_request_timeout'),
                opts=_params.get('opts'),
                collection_formats=_collection_formats,
                _request_auth=_params.get('_request_auth'), model_klass=packageModels)



